package com.maya.newbulgariankeyboard.main_utils

import com.maya.newbulgariankeyboard.R
import com.maya.newbulgariankeyboard.models.LatestMediaThemeModel
import com.maya.newbulgariankeyboard.models.LatestThemeModel

class LatestThemeFillerHelper {

    companion object {

        fun fillDefaultThemes(): ArrayList<LatestThemeModel> {
            val list = ArrayList<LatestThemeModel>()
            list.add(
                LatestThemeModel(
                    1,
                    "#E6E6E6",
                    "#000000",
                    "Default White",
                    "#E0E0E0",
                    "#E0E0E0"
                )
            )
            list.add(
                LatestThemeModel(
                    2,
                    "#000000",
                    "#FFFFFF",
                    "Default Dark",
                    "#212121",
                    "#212121"
                )
            )
            list.add(
                LatestThemeModel(
                    48,
                    "#E6E6E6",
                    "#000000",
                    "System Auto",
                    "#FDFDFD",
                    "#FF5A718C"
                )
            )

            return list
        }

        fun fillColoredThemes(): ArrayList<LatestThemeModel> {
            val list = ArrayList<LatestThemeModel>()
            list.add(
                LatestThemeModel(
                    3,
                    "#E9EDF0",
                    "#000000",
                    "Color",
                    "#FFFFFF",
                    "#cfd8dc"
                )
            )
            list.add(
                LatestThemeModel(
                    4,
                    "#E9EDF0",
                    "#000000",
                    "Default",
                    "#FDFDFD",
                    "#90caf9"
                )
            )
            list.add(
                LatestThemeModel(
                    5,
                    "#E9EDF0",
                    "#000000",
                    "Default",
                    "#FDFDFD",
                    "#f8bbd0"
                )
            )
            list.add(
                LatestThemeModel(
                    6,
                    "#E9EDF0",
                    "#000000",
                    "Default",
                    "#FDFDFD",
                    "#c5cae9"
                )
            )
            list.add(
                LatestThemeModel(
                    7,
                    "#E9EDF0",
                    "#000000",
                    "Default",
                    "#FDFDFD",
                    "#ffccbc"
                )
            )
            list.add(
                LatestThemeModel(
                    8,
                    "#E9EDF0",
                    "#000000",
                    "Color",
                    "#FFFFFF",
                    "#E9EDF0"
                )
            )
            list.add(
                LatestThemeModel(
                    9,
                    "#E9EDF0",
                    "#000000",
                    "Color",
                    "#E9EDF0",
                    "#cfd8dc"
                )
            )
            list.add(
                LatestThemeModel(
                    10,
                    "#fce4ec",
                    "#000000",
                    "Color",
                    "#FFFFFF",
                    "#f8bbd0"
                )
            )
            list.add(
                LatestThemeModel(
                    11,
                    "#E9EDF0",
                    "#000000",
                    "Color",
                    "#E9EDF0",
                    "#FFFFFF"
                )
            )
            list.add(
                LatestThemeModel(
                    12,
                    "#eeeeee",
                    "#000000",
                    "Color",
                    "#FFFFFF",
                    "#e0e0e0"
                )
            )
            list.add(
                LatestThemeModel(
                    13,
                    "#0E0927",
                    "#ffffff",
                    "Color",
                    "#0E0927",
                    "#111C39"
                )
            )
            list.add(
                LatestThemeModel(
                    14,
                    "#C62827",
                    "#ffffff",
                    "Color",
                    "#D34040",
                    "#F44236"
                )
            )
            list.add(
                LatestThemeModel(
                    15,
                    "#1564C0",
                    "#ffffff",
                    "Color",
                    "#1976d2",
                    "#2196F3"
                )
            )
            list.add(
                LatestThemeModel(
                    16,
                    "#43A047",
                    "#ffffff",
                    "Color",
                    "#64B267",
                    "#2D7E32"
                )
            )
            list.add(
                LatestThemeModel(
                    17,
                    "#00695B",
                    "#ffffff",
                    "Color",
                    "#2E8479",
                    "#4CB6AC"
                )
            )
            list.add(
                LatestThemeModel(
                    18,
                    "#45289F",
                    "#ffffff",
                    "Color",
                    "#664DB2",
                    "#7c4dff"
                )
            )
            list.add(
                LatestThemeModel(
                    19,
                    "#303f9f",
                    "#ffffff",
                    "Color",
                    "#3f51b5",
                    "#283593"
                )
            )
            list.add(
                LatestThemeModel(
                    20,
                    "#4D342F",
                    "#ffffff",
                    "Color",
                    "#795548",
                    "#8d6e63"
                )
            )
            list.add(
                LatestThemeModel(
                    21,
                    "#37474f",
                    "#ffffff",
                    "Color",
                    "#455a64",
                    "#546e7a"
                )
            )
            list.add(
                LatestThemeModel(
                    22,
                    "#0E0927",
                    "#ffffff",
                    "Color",
                    "#111C39",
                    "#00bcd4"
                )
            )
            list.add(
                LatestThemeModel(
                    23,
                    "#212121",
                    "#ffffff",
                    "Color",
                    "#424242",
                    "#616161"
                )
            )
            list.add(
                LatestThemeModel(
                    24,
                    "#546e7a",
                    "#ffffff",
                    "Color",
                    "#607d8b",
                    "#78909c"
                )
            )
            list.add(
                LatestThemeModel(
                    25,
                    "#fb8c00",
                    "#000000",
                    "Color",
                    "#ff9800",
                    "#ffa726"
                )
            )
            list.add(
                LatestThemeModel(
                    26,
                    "#ffa000",
                    "#000000",
                    "Color",
                    "#ffb300",
                    "#ffca28"
                )
            )
            list.add(
                LatestThemeModel(
                    27,
                    "#00796b",
                    "#ffffff",
                    "Color",
                    "#00897b",
                    "#26a69a"
                )
            )
            list.add(
                LatestThemeModel(
                    28,
                    "#ab47bc",
                    "#ffffff",
                    "Color",
                    "#ba68c8",
                    "#9c27b0"
                )
            )
            list.add(
                LatestThemeModel(
                    29,
                    "#689f38",
                    "#ffffff",
                    "Color",
                    "#7cb342",
                    "#8bc34a"
                )
            )
            list.add(
                LatestThemeModel(
                    30,
                    "#212121",
                    "#03B904",
                    "Color",
                    "#212121",
                    "#111111"
                )
            )
            list.add(
                LatestThemeModel(
                    31,
                    "#FD84D1",
                    "#ffffff",
                    "Color",
                    "#FF6DC8",
                    "#FD5AC0"
                )
            )
            list.add(
                LatestThemeModel(
                    32,
                    "#D0D5DB",
                    "#000000",
                    "Color",
                    "#FEFEFE",
                    "#BBC2CC"
                )
            )
            list.add(
                LatestThemeModel(
                    33,
                    "#FFDCE8",
                    "#000000",
                    "Color",
                    "#FCF8F9",
                    "#FAAEBA"
                )
            )
            list.add(
                LatestThemeModel(
                    34,
                    "#8080F1",
                    "#000000",
                    "Color",
                    "#8080F1",
                    "#8080F1"
                )
            )
            list.add(
                LatestThemeModel(
                    35,
                    "#CFD2DB",
                    "#000000",
                    "Color",
                    "#FFFFFF",
                    "#ABB1BD"
                )
            )
            list.add(
                LatestThemeModel(
                    36,
                    "#4AD295",
                    "#000000",
                    "Color",
                    "#4AD295",
                    "#4AD295"
                )
            )
            list.add(
                LatestThemeModel(
                    37,
                    "#AEE3D3",
                    "#000000",
                    "Color",
                    "#75FCDE",
                    "#02DEC4"
                )
            )
            list.add(
                LatestThemeModel(
                    38,
                    "#C1D4E3",
                    "#000000",
                    "Color",
                    "#9CBAD6",
                    "#96A8CE"
                )
            )
            list.add(
                LatestThemeModel(
                    39,
                    "#D9B6F6",
                    "#000000",
                    "Color",
                    "#FAF6F6",
                    "#FAF6F6"
                )
            )
            list.add(
                LatestThemeModel(
                    40,
                    "#F0F3F8",
                    "#000000",
                    "Color",
                    "#50C5D8E9",
                    "#60C5D8E9"
                )
            )
            list.add(
                LatestThemeModel(
                    41,
                    "#D0D3DC",
                    "#000000",
                    "Color",
                    "#FFFFFF",
                    "#A9B1BD"
                )
            )
            list.add(
                LatestThemeModel(
                    42,
                    "#5FB7D8",
                    "#FFFFFF",
                    "Color",
                    "#40EBF7FA",
                    "#60EBF7FA"
                )
            )
            list.add(
                LatestThemeModel(
                    43,
                    "#DAB88A",
                    "#000000",
                    "Color",
                    "#FCFBE7",
                    "#FCFBE7"
                )
            )
            list.add(
                LatestThemeModel(
                    44,
                    "#F9FEF8",
                    "#000000",
                    "Color",
                    "#C8EDA3",
                    "#BCED97"
                )
            )
            list.add(
                LatestThemeModel(
                    45,
                    "#CCECFB",
                    "#000000",
                    "Color",
                    "#9DD5EE",
                    "#9DD5EE"
                )
            )
            list.add(
                LatestThemeModel(
                    46,
                    "#F0F0F0",
                    "#000000",
                    "Color",
                    "#FCFCFC",
                    "#FCFCFC"
                )
            )
            list.add(
                LatestThemeModel(
                    47,
                    "#FDCDAA",
                    "#000000",
                    "Color",
                    "#FA9063",
                    "#FA9063"
                )
            )
            list.add(
                LatestThemeModel(
                    48,
                    "#EDEAD7",
                    "#000000",
                    "Color",
                    "#F6F5FA",
                    "#F6F5FA"
                )
            )
            list.add(
                LatestThemeModel(
                    49,
                    "#FFD6DA",
                    "#000000",
                    "Color",
                    "#FAA0A5",
                    "#FAA0A5"
                )
            )
            list.add(
                LatestThemeModel(
                    50,
                    "#25252F",
                    "#FFFFFF",
                    "Color",
                    "#3F3E4E",
                    "#3F3E4E"
                )
            )
            return list
        }

        fun fillLightGradientThemes(): ArrayList<LatestMediaThemeModel> {
            val list = ArrayList<LatestMediaThemeModel>()
            list.add(
                LatestMediaThemeModel(
                    51,
                    R.drawable.bg_shape_light_gradient_1,
                    "#000000",
                    "Color", "#FAF7FF", "#C599FF"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    52,
                    R.drawable.bg_shape_light_gradient_2,
                    "#000000",
                    "Color", "#40ffffff", "#c9d7d8"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    53,
                    R.drawable.bg_shape_light_gradient_3,
                    "#000000",
                    "Color", "#40ffffff", "#bbc5cf"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    54,
                    R.drawable.bg_shape_light_gradient_4,
                    "#000000",
                    "Color", "#40ffffff", "#b1b1b3"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    55,
                    R.drawable.bg_shape_light_gradient_5,
                    "#000000",
                    "Color", "#40ffffff", "#f394b4"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    56,
                    R.drawable.bg_shape_light_gradient_6,
                    "#000000",
                    "Color", "#40ffffff", "#b7eafd"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    57,
                    R.drawable.bg_shape_light_gradient_7,
                    "#000000",
                    "Color", "#40ffffff", "#dcd9f8"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    58,
                    R.drawable.bg_shape_light_gradient_8,
                    "#000000",
                    "Color", "#40ffffff", "#e5c9d2"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    59,
                    R.drawable.bg_shape_light_gradient_9,
                    "#000000",
                    "Color", "#40ffffff", "#fee5b2"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    60,
                    R.drawable.bg_shape_light_gradient_10,
                    "#000000",
                    "Color", "#40ffffff", "#d5e5fa"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    61,
                    R.drawable.bg_shape_light_gradient_11,
                    "#000000",
                    "Color", "#40ffffff", "#fdb6aa"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    62,
                    R.drawable.bg_shape_light_gradient_12,
                    "#000000",
                    "Color", "#40ffffff", "#d9d893"
                )
            )
            return list
        }

        fun fillDarkGradientThemes(): ArrayList<LatestMediaThemeModel> {
            val list = ArrayList<LatestMediaThemeModel>()
            list.add(
                LatestMediaThemeModel(
                    63,
                    R.drawable.bg_shape_dark_gradient_1,
                    "#ffffff",
                    "Color", "#40ffffff", "#2a176d"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    64,
                    R.drawable.bg_shape_dark_gradient_2,
                    "#ffffff",
                    "Color", "#40ffffff", "#505358"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    65,
                    R.drawable.bg_shape_dark_gradient_3,
                    "#ffffff",
                    "Color", "#40ffffff", "#5b443e"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    66,
                    R.drawable.bg_shape_dark_gradient_4,
                    "#ffffff",
                    "Color", "#40ffffff", "#4b5c64"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    67,
                    R.drawable.bg_shape_dark_gradient_5,
                    "#ffffff",
                    "Color", "#40ffffff", "#017769"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    68,
                    R.drawable.bg_shape_dark_gradient_6,
                    "#ffffff",
                    "Color", "#40ffffff", "#146bd4"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    69,
                    R.drawable.bg_shape_dark_gradient_7,
                    "#ffffff",
                    "Color", "#40ffffff", "#355b80"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    70,
                    R.drawable.bg_shape_dark_gradient_8,
                    "#ffffff",
                    "Color", "#40ffffff", "#515459"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    71,
                    R.drawable.bg_shape_dark_gradient_9,
                    "#ffffff",
                    "Color", "#40ffffff", "#605654"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    72,
                    R.drawable.bg_shape_dark_gradient_10,
                    "#ffffff",
                    "Color", "#40ffffff", "#054d49"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    73,
                    R.drawable.bg_shape_dark_gradient_11,
                    "#ffffff",
                    "Color", "#40ffffff", "#03747a"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    74,
                    R.drawable.bg_shape_dark_gradient_12,
                    "#ffffff",
                    "Color", "#40ffffff", "#767096"
                )
            )
            return list
        }

        fun fillLandscapesThemes(): ArrayList<LatestMediaThemeModel> {
            val list = ArrayList<LatestMediaThemeModel>()
            list.add(
                LatestMediaThemeModel(
                    75,
                    R.drawable.ic_photos_theme_1,
                    "#ffffff",
                    "Color", "#40ffffff", "#80ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    76,
                    R.drawable.ic_photos_theme_2,
                    "#ffffff",
                    "Color", "#604E578D", "#804E578D"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    77,
                    R.drawable.ic_photos_theme_3,
                    "#ffffff",
                    "Color", "#40FC995C", "#60FC995C"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    78,
                    R.drawable.ic_photos_theme_4,
                    "#ffffff",
                    "Color", "#50023F7E", "#80023F7E"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    79,
                    R.drawable.ic_photos_theme_5,
                    "#ffffff",
                    "Color", "#50811727", "#80811727"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    80,
                    R.drawable.ic_photos_theme_6,
                    "#ffffff",
                    "Color", "#40ffffff", "#80ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    81,
                    R.drawable.ic_photos_theme_7,
                    "#ffffff",
                    "Color", "#50104D8B", "#80104D8B"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    82,
                    R.drawable.ic_photos_theme_8,
                    "#ffffff",
                    "Color", "#40ffffff", "#80ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    83,
                    R.drawable.ic_photos_theme_9,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    84,
                    R.drawable.ic_photos_theme_10,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    85,
                    R.drawable.ic_photos_theme_11,
                    "#ffffff",
                    "Color", "#30ffffff", "#60ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    86,
                    R.drawable.ic_photos_theme_12,
                    "#ffffff",
                    "Color", "#40ffffff", "#80ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    87,
                    R.drawable.ic_photos_theme_13,
                    "#ffffff",
                    "Color", "#30ffffff", "#60ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    88,
                    R.drawable.ic_photos_theme_14,
                    "#ffffff",
                    "Color", "#40ffffff", "#80ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    89,
                    R.drawable.ic_photos_theme_15,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    90,
                    R.drawable.ic_photos_theme_16,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    91,
                    R.drawable.ic_photos_theme_17,
                    "#ffffff",
                    "Color", "#50B39C2A", "#80B39C2A"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    92,
                    R.drawable.ic_photos_theme_18,
                    "#FFFEFE",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    93,
                    R.drawable.ic_photos_theme_19,
                    "#ffffff",
                    "Color", "#40ffffff", "#80ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    94,
                    R.drawable.ic_photos_theme_20,
                    "#ffffff",
                    "Color", "#50074FD0", "#80074FD0"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    95,
                    R.drawable.ic_photos_theme_21,
                    "#ffffff",
                    "Color", "#50245876", "#80245876"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    96,
                    R.drawable.ic_photos_theme_22,
                    "#FFFFFF",
                    "Color", "#50130181", "#80130181"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    97,
                    R.drawable.ic_photos_theme_23,
                    "#FFFFFF",
                    "Color", "#50DE9962", "#80DE9962"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    98,
                    R.drawable.ic_photos_theme_24,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    99,
                    R.drawable.ic_photos_theme_25,
                    "#ffffff",
                    "Color", "#50012B34", "#80012B34"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    100,
                    R.drawable.ic_photos_theme_26,
                    "#ffffff",
                    "Color", "#500A2657", "#800A2657"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    101,
                    R.drawable.ic_photos_theme_27,
                    "#ffffff",
                    "Color", "#50BA4F25", "#80BA4F25"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    102,
                    R.drawable.ic_photos_theme_28,
                    "#ffffff",
                    "Color", "#808B4083", "#908B4083"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    103,
                    R.drawable.ic_photos_theme_29,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    104,
                    R.drawable.ic_photos_theme_30,
                    "#FFFFFF",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    105,
                    R.drawable.ic_photos_theme_31,
                    "#FFFFFF",
                    "Color", "#804B4583", "#804B4583"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    106,
                    R.drawable.ic_photos_theme_32,
                    "#FFFFFF",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    107,
                    R.drawable.ic_photos_theme_33,
                    "#FEFFFF",
                    "Color", "#402B2B2D", "#602B2B2D"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    108,
                    R.drawable.ic_photos_theme_34,
                    "#FEFFFF",
                    "Color", "#50907E42", "#80907E42"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    109,
                    R.drawable.ic_photos_theme_35,
                    "#FEFFFF",
                    "Color", "#60040312", "#80040312"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    111,
                    R.drawable.ic_photos_theme_36,
                    "#FEFFFF",
                    "Color", "#50515C89", "#80515C89"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    112,
                    R.drawable.ic_photos_theme_37,
                    "#FEFFFF",
                    "Color", "#40613642", "#80613642"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    113,
                    R.drawable.ic_photos_theme_38,
                    "#FFFFFF",
                    "Color", "#40080606", "#60080606"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    114,
                    R.drawable.ic_photos_theme_39,
                    "#ffffff",
                    "Color", "#30ffffff", "#50ffffff"
                )
            )
            list.add(
                LatestMediaThemeModel(
                    115,
                    R.drawable.ic_photos_theme_40,
                    "#FFFFFF",
                    "Color", "#50520E43", "#80520E43"
                )
            )

            return list
        }
    }
}