package com.maya.newbulgariankeyboard.media_inputs.keyboard_stickers

class LatestStickersFillerHelper {

    companion object{

        fun fillStickersListOne(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(1, "https://drive.google.com/uc?export=download&id=1BC7xMYygx6ARLAo-gr-eYcUio1xx8gQf"))
            list.add(LatestStickerModel(2, "https://drive.google.com/uc?export=download&id=1qZA7G32ZNMVbH5vARKq2LcslTdtpfXwt"))
            list.add(LatestStickerModel(3, "https://drive.google.com/uc?export=download&id=11sEN1EJ2nap8Vncp-UrF9nDFsteOMutY"))
            list.add(LatestStickerModel(4, "https://drive.google.com/uc?export=download&id=1o650X7P76YOO04pXwyZoYWGNG1xPqolc"))
            list.add(LatestStickerModel(5, "https://drive.google.com/uc?export=download&id=1dR1e-2hwV7LKJASvnfMKJnERgJYDz2Bb"))
            list.add(LatestStickerModel(6, "https://drive.google.com/uc?export=download&id=1qNbeX16kdPfy6ZJhbOms-iSMPlmFCKWw"))
            list.add(LatestStickerModel(7, "https://drive.google.com/uc?export=download&id=1blcxoioPEDsjI9vTCdEm7HrkLeXgivS-"))
            list.add(LatestStickerModel(8, "https://drive.google.com/uc?export=download&id=1T_bHiJQEeLRkyZXV52pNu5Nl2NAlqHHL"))
            list.add(LatestStickerModel(9, "https://drive.google.com/uc?export=download&id=1b_6h_uYVtSJSvCRqU-4Rg5qlrBx7Oh1r"))
            list.add(LatestStickerModel(10, "https://drive.google.com/uc?export=download&id=1ykPwQkykllDgqktcl1sE3riCrOp4FZJ2"))
            list.add(LatestStickerModel(11, "https://drive.google.com/uc?export=download&id=1ht9S9cHroO5WrPT1HGRiXKQ-k8Ccfqjy"))
            list.add(LatestStickerModel(12, "https://drive.google.com/uc?export=download&id=12ieYfn6--pRbCKkrzLNkBSabfQxBs2jG"))
            list.add(LatestStickerModel(13, "https://drive.google.com/uc?export=download&id=1kJITh-FEYjT1_buEyY9130cYdokaAqyp"))
            list.add(LatestStickerModel(14, "https://drive.google.com/uc?export=download&id=1VQntMFlKj6IY9vrm7uPaQMdXcdGuH3yN"))
            list.add(LatestStickerModel(15, "https://drive.google.com/uc?export=download&id=1tHrKjICP2dIoyGUngGQm88IF4sLaBgFG"))
            list.add(LatestStickerModel(16, "https://drive.google.com/uc?export=download&id=1nHQzHwvIM7YfM-cjbQIvcLPLEtXPT6AH"))
            list.add(LatestStickerModel(17, "https://drive.google.com/uc?export=download&id=1GaTbjZyuGF-O7VpJw9kOVLYy35iVFd5J"))
            list.add(LatestStickerModel(18, "https://drive.google.com/uc?export=download&id=1Dd7u0dOiZV3ZKarF-T_rSF7RSyLzEW3e"))
            list.add(LatestStickerModel(19, "https://drive.google.com/uc?export=download&id=1ZF-FLBQrbURmuwM0bKtPILWcDLxPRvy5"))
            list.add(LatestStickerModel(20, "https://drive.google.com/uc?export=download&id=1MDPLFj8OWDGCWi6LTezuPkkV5_qm5lUz"))
            list.add(LatestStickerModel(21, "https://drive.google.com/uc?export=download&id=1NXUr8HE8nC7k8TjEw0R5ymm6ENS5adCT"))
            list.add(LatestStickerModel(22, "https://drive.google.com/uc?export=download&id=1peSwQaXIGJezREFC6FaEw7L9qWo446Gy"))
            list.add(LatestStickerModel(23, "https://drive.google.com/uc?export=download&id=1qVlieI7TFrF8nnAU8nFb331ku-a8H-dw"))
            list.add(LatestStickerModel(24, "https://drive.google.com/uc?export=download&id=1RCY_YPRMOsby54w10BEwYAOuTkfkQEYa"))
            list.add(LatestStickerModel(25, "https://drive.google.com/uc?export=download&id=14XKYV0azlt2haXmpGmFqqavkAbJ5lFZl"))
            list.add(LatestStickerModel(26, "https://drive.google.com/uc?export=download&id=1BbIjnCU0i-ZrZOpRpPh-UH0bnHCU_4fZ"))
            list.add(LatestStickerModel(27, "https://drive.google.com/uc?export=download&id=1gmY_xFlVgx0Li5f0ENtv7oZI0bBTj0hm"))
            list.add(LatestStickerModel(28, "https://drive.google.com/uc?export=download&id=1Bv2wxIWPCX2qTNkPSpmFHHMsv0UZMx3f"))
            list.add(LatestStickerModel(29, "https://drive.google.com/uc?export=download&id=1UoE_yDWupJ2zMncC_FLVCB-mTnQHW2y-"))
            list.add(LatestStickerModel(30, "https://drive.google.com/uc?export=download&id=1bPGmQjNfZ7HbMsndWOI4yTSGNvA0Ijgv"))
            return list
        }


        fun fillStickersListTwo(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(31, "https://drive.google.com/uc?export=download&id=1y03cihrpkBvR6OkhTk3k0i2D0MjB1Q0I"))
            list.add(LatestStickerModel(32, "https://drive.google.com/uc?export=download&id=129RVPhThjv6UQmJIJYHbk9KYmRIgvMyp"))
            list.add(LatestStickerModel(33, "https://drive.google.com/uc?export=download&id=1VOW9AAj96yi4E8WarFfWMvuZGJUBy0Nh"))
            list.add(LatestStickerModel(34, "https://drive.google.com/uc?export=download&id=1zDaNBdNpBnIyD_3ER2-P-NfdVNXxUP_7"))
            list.add(LatestStickerModel(35, "https://drive.google.com/uc?export=download&id=1iAG_SSjoezxAEdr7Oh4VqHAd91UgqsIe"))
            list.add(LatestStickerModel(36, "https://drive.google.com/uc?export=download&id=1mkSDTUKh94xhzlWrvyFoLffOz50qVrju"))
            list.add(LatestStickerModel(37, "https://drive.google.com/uc?export=download&id=1UNsRA2jJW_yp4YvofryieGXezyn5bHkG"))
            list.add(LatestStickerModel(38, "https://drive.google.com/uc?export=download&id=19pNxazbFhcD_9uTA5dYimc91wiWdirsW"))
            list.add(LatestStickerModel(39, "https://drive.google.com/uc?export=download&id=1NltaeNoT0FFqcUNzeEeilwvdSEGpx5Fh"))
            list.add(LatestStickerModel(40, "https://drive.google.com/uc?export=download&id=18ixL03uF3kn7MjsrOtOztT9h1I34uB2W"))
            list.add(LatestStickerModel(41, "https://drive.google.com/uc?export=download&id=1ZBmiyDw5Y7EYmAnnWWJQPUQhTRGanwo0"))
            list.add(LatestStickerModel(42, "https://drive.google.com/uc?export=download&id=18cwKgMW5p1zaxU0pczWPqRaamCfQ9dUB"))
            list.add(LatestStickerModel(43, "https://drive.google.com/uc?export=download&id=1iTA7lxz4d2HZdlVK7HdoGQrRKwbHEW7s"))
            list.add(LatestStickerModel(44, "https://drive.google.com/uc?export=download&id=19u4oUp6DBK3zViqOIET362Lnh8dC3PPf"))
            list.add(LatestStickerModel(45, "https://drive.google.com/uc?export=download&id=1yS86RCg3O8Z3BAFjEj3sR2BtC2Z7Ebhy"))
            list.add(LatestStickerModel(46, "https://drive.google.com/uc?export=download&id=1S5Z-G3qNsIycSe0tgQ4_9ZT2HLk3M7Di"))
            list.add(LatestStickerModel(47, "https://drive.google.com/uc?export=download&id=1KEt0WgqBTCYX5KHqkOUnEJAdzvVIvIwP"))
            list.add(LatestStickerModel(48, "https://drive.google.com/uc?export=download&id=12gRAMxjCH4e0R9SulwzW4QQd_cGLWkgA"))
            list.add(LatestStickerModel(49, "https://drive.google.com/uc?export=download&id=1lZSY59qsgGRSchTQVoTn0MsgnufnLQoA"))
            list.add(LatestStickerModel(50, "https://drive.google.com/uc?export=download&id=1X9huUiiVdbGGQVCW23y-MV1jH2hb7NNs"))
            list.add(LatestStickerModel(51, "https://drive.google.com/uc?export=download&id=15w1xIqgQiRKHSPMVlW0MJV7xOktqy-9x"))
            list.add(LatestStickerModel(52, "https://drive.google.com/uc?export=download&id=1mP3W7sgUMo104e57yWnN_YgDYIxbkl5d"))
            list.add(LatestStickerModel(53, "https://drive.google.com/uc?export=download&id=1ZHZWMPFEJPkz9wZYN_0oiXVsKx5S0EMn"))
            list.add(LatestStickerModel(54, "https://drive.google.com/uc?export=download&id=1RbMNqxDgDrGl70GMk7fdD-1AiRYIhk36"))
            list.add(LatestStickerModel(55, "https://drive.google.com/uc?export=download&id=17U6SGtv6MmipU1KW_BjOolof6suL7YsH"))
            list.add(LatestStickerModel(56, "https://drive.google.com/uc?export=download&id=1HviAyjOY100sgNQGL1aW7Rj7-9Sb-NxS"))
            list.add(LatestStickerModel(57, "https://drive.google.com/uc?export=download&id=1n_XEwIWxOIWhvg_zVVRGmneHy0JGRC0H"))
            list.add(LatestStickerModel(58, "https://drive.google.com/uc?export=download&id=1YuFwO9FEbbEc-qHNbai78U1ruysKF1Ff"))
            list.add(LatestStickerModel(59, "https://drive.google.com/uc?export=download&id=1_6eSTyqe7vSm0V6FjPiUOXM5MoVO-8GB"))
            list.add(LatestStickerModel(60, "https://drive.google.com/uc?export=download&id=11dmPbfbFSmXXkLE-PJu98NTzEAgxmm_G"))
            return list
        }


        fun fillStickersListThree(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(61, "https://drive.google.com/uc?export=download&id=12sf-MNG2oTFH0lCclwRQOr7Nl-dQTWCT"))
            list.add(LatestStickerModel(62, "https://drive.google.com/uc?export=download&id=1SEnSiqsdq29JMxPoygVoaWd6jDxbAWYo"))
            list.add(LatestStickerModel(63, "https://drive.google.com/uc?export=download&id=1MyL1QQX_Ay1BKY4UuuImPDYKuLDKbfhh"))
            list.add(LatestStickerModel(64, "https://drive.google.com/uc?export=download&id=1xGC7CODr1MdXYMo7ej6DVUruAnrj6Xq7"))
            list.add(LatestStickerModel(65, "https://drive.google.com/uc?export=download&id=1OpmKVtz5WAT0kcCXLJoB_TuBxbuav4f9"))
            list.add(LatestStickerModel(66, "https://drive.google.com/uc?export=download&id=1n9xyhYr8x9hibcZOZUr7ttHFAOwQvOG1"))
            list.add(LatestStickerModel(67, "https://drive.google.com/uc?export=download&id=1QxvUUuy7Q05Bcq3QnU6W4_Y8CZQ6XJrB"))
            list.add(LatestStickerModel(68, "https://drive.google.com/uc?export=download&id=1Kkn0meWqnCNft_cYu8RBoovoj10QpJEs"))
            list.add(LatestStickerModel(69, "https://drive.google.com/uc?export=download&id=1PdZ2PtxlR7TYkV52kqPt-ZOgJOH-dH0C"))
            list.add(LatestStickerModel(70, "https://drive.google.com/uc?export=download&id=1kNO5fqpWd6J9NYwRy41WD_JSOgc4SdT8"))
            list.add(LatestStickerModel(71, "https://drive.google.com/uc?export=download&id=1DqHHCDp7qOF40nN8-3G2pOwUEwepuRrx"))
            list.add(LatestStickerModel(72, "https://drive.google.com/uc?export=download&id=1eAILZXYdN6_WaNSqyCz4pHFejkhKM2eu"))
            list.add(LatestStickerModel(73, "https://drive.google.com/uc?export=download&id=1XUnr_LBlV1L296ODwy-eiy53-0PMVNEd"))
            list.add(LatestStickerModel(74, "https://drive.google.com/uc?export=download&id=1x202qzYPIrBpPA6OzSbRYOghgZH29BDX"))
            list.add(LatestStickerModel(75, "https://drive.google.com/uc?export=download&id=1H_8F1H8EtoNdnvOoyEu-eVIUMQfU5lY3"))
            list.add(LatestStickerModel(76, "https://drive.google.com/uc?export=download&id=1XFTNt2MdFQeFBxMDz5VTD6eWjSsVN1q6"))
            list.add(LatestStickerModel(77, "https://drive.google.com/uc?export=download&id=13ghgRPRmGSFtETMdpEyYCbwBcR7Rh68p"))
            list.add(LatestStickerModel(78, "https://drive.google.com/uc?export=download&id=1K6U9K92unXmjR01MX9WJ6CVtbhvLoFZw"))
            list.add(LatestStickerModel(79, "https://drive.google.com/uc?export=download&id=1Yz2dUl6HcG5BPx-Dht_UGXaGRQ5fAqtL"))
            list.add(LatestStickerModel(80, "https://drive.google.com/uc?export=download&id=1EFYWdmjA3L805J2fckdbAMK77d5tv0HV"))
            list.add(LatestStickerModel(81, "https://drive.google.com/uc?export=download&id=108RO1ab2YPRwruWat0JEdM7oQhWLAAlV"))
            list.add(LatestStickerModel(82, "https://drive.google.com/uc?export=download&id=1gKMAQ6e2m_lZRSe3js6yov9StC6HJZR2"))
            list.add(LatestStickerModel(83, "https://drive.google.com/uc?export=download&id=1WXv9HRldVx245QfjmTeTMuRT0NnXCCBh"))
            list.add(LatestStickerModel(84, "https://drive.google.com/uc?export=download&id=1S0jgugOAEod6tIbSkVwhFhSKMlyB0wRG"))
            list.add(LatestStickerModel(85, "https://drive.google.com/uc?export=download&id=1O16Au1pSokXE_SuS3c9SCAkjzhmwOmJG"))
            list.add(LatestStickerModel(86, "https://drive.google.com/uc?export=download&id=1iliAdKtsTVGMQZBblcnSbTQnACbbp1DE"))
            list.add(LatestStickerModel(87, "https://drive.google.com/uc?export=download&id=1GPWE0uuIw2ONJi8gipqKZwG19OipJmMJ"))
            list.add(LatestStickerModel(88, "https://drive.google.com/uc?export=download&id=1oE24ssrxPvqyOC0IiiBpxmK7Ox_BAk7G"))
            list.add(LatestStickerModel(89, "https://drive.google.com/uc?export=download&id=1FAxii5Tz-F4nsCS65Jcoo_woFi_7r1Qk"))
            list.add(LatestStickerModel(90, "https://drive.google.com/uc?export=download&id=1OtisVHfG4_4zJ13ggT4yHMDBsvrI6GvZ"))
            return list
        }


        fun fillStickersListFour(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(91, "https://drive.google.com/uc?export=download&id=1Od25StNaL9yP0yJikLH6QAlPd8cc52aY"))
            list.add(LatestStickerModel(92, "https://drive.google.com/uc?export=download&id=1q0B_YmX8Mk-sY7SFXHW_zmDcVFDpC668"))
            list.add(LatestStickerModel(93, "https://drive.google.com/uc?export=download&id=1R0k9F8N7pJI9VZPKUxSZz1RU6By5UsAK"))
            list.add(LatestStickerModel(94, "https://drive.google.com/uc?export=download&id=1u40FNYLePtMETfZEdrvrzDtmQJYP8BZB"))
            list.add(LatestStickerModel(95, "https://drive.google.com/uc?export=download&id=1a6Dw42vY3-YUPBsIqUEAxU18TyDdWuGL"))
            list.add(LatestStickerModel(96, "https://drive.google.com/uc?export=download&id=1Zv4TcpAVBHf6zNTcfC4Iu2QJeZ6j6nUW"))
            list.add(LatestStickerModel(97, "https://drive.google.com/uc?export=download&id=1mY9NSWXeXp8BZ0UEqDZRPV3KVIEsSq90"))
            list.add(LatestStickerModel(98, "https://drive.google.com/uc?export=download&id=12N6pRsOB4Z19z8pzU7ZyMSFJTCGKP-KY"))
            list.add(LatestStickerModel(99, "https://drive.google.com/uc?export=download&id=10GuZMgmGdkH6SQbtK9f1nEQ-OftygTEm"))
            list.add(LatestStickerModel(100, "https://drive.google.com/uc?export=download&id=1JMp5Q7R99KeCoZYGewUG1O0s3Eb4PFGv"))
            list.add(LatestStickerModel(101, "https://drive.google.com/uc?export=download&id=1ylA9yxbHEXOvDvHPIJCNStLO4GAyoG5i"))
            list.add(LatestStickerModel(102, "https://drive.google.com/uc?export=download&id=1_2K8zbsalMxwYzaGMoZgIuJi45pyR2nA"))
            list.add(LatestStickerModel(103, "https://drive.google.com/uc?export=download&id=1VYSApjEhigY0kp_QqJc2EBLQbjS_UOQ3"))
            list.add(LatestStickerModel(104, "https://drive.google.com/uc?export=download&id=1HwvvGfslq4YElE6Yp_SbhsW7qgG-jtAy"))
            list.add(LatestStickerModel(105, "https://drive.google.com/uc?export=download&id=17fBPzKUxb61ZEoHnA7JVptvw5UaIPMbs"))
            list.add(LatestStickerModel(106, "https://drive.google.com/uc?export=download&id=1R3OenpAVmsUhdI5hkT7_1VZ6kwomVG5B"))
            list.add(LatestStickerModel(107, "https://drive.google.com/uc?export=download&id=1m9H8RifzrHYdU3oTuRqwJIdWcQPfAjEo"))
            list.add(LatestStickerModel(108, "https://drive.google.com/uc?export=download&id=1uKLXqMiwAmoSi8dXMYlzRNtlxAAkgAo3"))
            list.add(LatestStickerModel(109, "https://drive.google.com/uc?export=download&id=1ZbeDuyVooASZeb4NO0CyIGQgojMmfA4o"))
            list.add(LatestStickerModel(110, "https://drive.google.com/uc?export=download&id=1p6-QUiCuz23ClVFi7SkOr64NH2woIW4t"))
            list.add(LatestStickerModel(111, "https://drive.google.com/uc?export=download&id=11Cw5I-jbDPNxjp2wzAQn1qIz9joRlqvY"))
            list.add(LatestStickerModel(112, "https://drive.google.com/uc?export=download&id=1r5R1RruUIYv-UZEesYPBbUCsgcRqc1kb"))
            list.add(LatestStickerModel(113, "https://drive.google.com/uc?export=download&id=1Yuo8vGPEecca-Kxg6Bv2O6RePmUyChIp"))
            list.add(LatestStickerModel(114, "https://drive.google.com/uc?export=download&id=1kdNKMObYNr8SkglcVx__xsrSA4F-XWqf"))
            list.add(LatestStickerModel(115, "https://drive.google.com/uc?export=download&id=1BgD0GvdvegokP5HWtuu_ZZl0slgMDsZG"))
            list.add(LatestStickerModel(116, "https://drive.google.com/uc?export=download&id=1w_GOzbpqYzyQaWEfvqBCEw4-IUa-9nIm"))
            list.add(LatestStickerModel(117, "https://drive.google.com/uc?export=download&id=1QyC_kZaeTC0zm1GEZnYNt1Wqb2GTKNHt"))
            list.add(LatestStickerModel(118, "https://drive.google.com/uc?export=download&id=1d4E0J1F930bhnBgIB0VQQfO8qsbbNe53"))
            list.add(LatestStickerModel(119, "https://drive.google.com/uc?export=download&id=1j3Z61KcJbAErpi-BT01mzVxMI_ZwF7lD"))
            list.add(LatestStickerModel(120, "https://drive.google.com/uc?export=download&id=1bGjsE9SWHgyX8gzd24rJi_GyTkUzlZI4"))
            return list
        }


        fun fillStickersListFive(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(121, "https://drive.google.com/uc?export=download&id=11n8xGdjhGibrxoONYDeBa9tuntth1mG8"))
            list.add(LatestStickerModel(122, "https://drive.google.com/uc?export=download&id=1wL-WqqYBPxfiFXLkzuyG-pYGPzg0dPTz"))
            list.add(LatestStickerModel(123, "https://drive.google.com/uc?export=download&id=11Pi_pmNSL9-ufdI9DOeUVAe9E5X6PM6S"))
            list.add(LatestStickerModel(124, "https://drive.google.com/uc?export=download&id=15AZB1aG7sCF4JWpUl6jRkvOLzU0tGRFC"))
            list.add(LatestStickerModel(125, "https://drive.google.com/uc?export=download&id=1R8cpT7rAJn_MdDoFfn7egFzxvVjWDImN"))
            list.add(LatestStickerModel(126, "https://drive.google.com/uc?export=download&id=1fVMWGzsDWuzieP28wOivqtU2QwjOkohB"))
            list.add(LatestStickerModel(127, "https://drive.google.com/uc?export=download&id=10n_UJYlFLV3QD8FNDRm00zCGWlD7bfGW"))
            list.add(LatestStickerModel(128, "https://drive.google.com/uc?export=download&id=12V35O7jHIcX_tmzqmV6bfF2QEFD_j9rc"))
            list.add(LatestStickerModel(129, "https://drive.google.com/uc?export=download&id=1TtkZeGJ63G6yJH6ieF8Qzpp8QIYxScZ6"))
            list.add(LatestStickerModel(130, "https://drive.google.com/uc?export=download&id=1Idtvah-h4ss3AybYZ8vPlaCI0txjyXif"))
            list.add(LatestStickerModel(131, "https://drive.google.com/uc?export=download&id=1BRt0DXcyVItK3wl8Hy35MOaEu6kvOG6J"))
            list.add(LatestStickerModel(132, "https://drive.google.com/uc?export=download&id=1LwIYr1Wpu6SlJxlp1G-uB-p8YzIaz-wD"))
            list.add(LatestStickerModel(133, "https://drive.google.com/uc?export=download&id=1_k_LBo5u5mUo4-5C8UJP5LBw_zpM3C-C"))
            list.add(LatestStickerModel(134, "https://drive.google.com/uc?export=download&id=11Cn5tL4tH_5BV8PWRyLf-0jLVpKP1b5a"))
            list.add(LatestStickerModel(135, "https://drive.google.com/uc?export=download&id=1kIzbrCHkD8QNsI1LslhqX6nSawy2Zq56"))
            list.add(LatestStickerModel(136, "https://drive.google.com/uc?export=download&id=1VbuUKAQtxqPePXRfH6e0TRRisZyQEOeq"))
            list.add(LatestStickerModel(137, "https://drive.google.com/uc?export=download&id=1DaBLM9hRegt0ZhR2bRNcqiFzlCt_aKPA"))
            list.add(LatestStickerModel(138, "https://drive.google.com/uc?export=download&id=16mh7m8SDrova9bq2S7Ry6k-d4NckTg9B"))
            list.add(LatestStickerModel(139, "https://drive.google.com/uc?export=download&id=1H-gyQWPtnUYQTfWgALsFtdne6ptfheCt"))
            list.add(LatestStickerModel(140, "https://drive.google.com/uc?export=download&id=1czVDSBjSx7Arm6Wmee_tSopyLvRk39Az"))
            list.add(LatestStickerModel(141, "https://drive.google.com/uc?export=download&id=1ljBI8jFbfFZ2HZHPx1pzfdHRFx0hp9CI"))
            list.add(LatestStickerModel(142, "https://drive.google.com/uc?export=download&id=16aseub0zvjQaU9AknqglpYU9qPLSENlh"))
            list.add(LatestStickerModel(143, "https://drive.google.com/uc?export=download&id=1yI7yLVREHlLJ2lGv16ofoaZus1vpdrca"))
            list.add(LatestStickerModel(144, "https://drive.google.com/uc?export=download&id=16oQ8pICzK58qCzJIUHFvpEhXsMrPWC1V"))
            list.add(LatestStickerModel(145, "https://drive.google.com/uc?export=download&id=1j8cEGZlhW5cyui-R8YGmctvjtI2xSOq8"))
            list.add(LatestStickerModel(146, "https://drive.google.com/uc?export=download&id=1mjiCF2HJsQwpd29VlEGmBXeCgITeLHY1"))
            list.add(LatestStickerModel(147, "https://drive.google.com/uc?export=download&id=1O_TeWrL7PUERrffn8g0BmND7zeGTci4z"))
            list.add(LatestStickerModel(148, "https://drive.google.com/uc?export=download&id=12RMCD5xNRilGW3qm_yxmY-LEpzqGnY-t"))
            list.add(LatestStickerModel(149, "https://drive.google.com/uc?export=download&id=1EVN3eQKOdIkS_QYYQfM3d6lNwQODT5W0"))
            list.add(LatestStickerModel(150, "https://drive.google.com/uc?export=download&id=1jHHm-wnO7smcUETeewLORNwMulqnnTJf"))
            return list
        }


        fun fillStickersListSix(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(151, "https://drive.google.com/uc?export=download&id=1_e039RrBnrxtPRB25EmLw-L-plcUui7v"))
            list.add(LatestStickerModel(152, "https://drive.google.com/uc?export=download&id=16L4kcTHlKJW8HthYU48uA2Rt7DlfZXMf"))
            list.add(LatestStickerModel(153, "https://drive.google.com/uc?export=download&id=1iK3AjEwtqnbsp5moTSuDQD8HRxozfol1"))
            list.add(LatestStickerModel(154, "https://drive.google.com/uc?export=download&id=1qNYDmc5eZRXuGpR9vSiMDvk295bWu_mt"))
            list.add(LatestStickerModel(155, "https://drive.google.com/uc?export=download&id=1R2XKDYGE3MTJoKkrY7-iBKGjRNRBr9tg"))
            list.add(LatestStickerModel(156, "https://drive.google.com/uc?export=download&id=1umWSxODdfun7d5nskBEPEMiOy1PNAGr4"))
            list.add(LatestStickerModel(157, "https://drive.google.com/uc?export=download&id=1rFG2-FtGtXOGSIpYmIpeWEqXuDU_LJEf"))
            list.add(LatestStickerModel(158, "https://drive.google.com/uc?export=download&id=1c5jlVTxsW7d4XHrgMqDgo3YNv_1cYcBp"))
            list.add(LatestStickerModel(159, "https://drive.google.com/uc?export=download&id=1ennWJ2_ocX_efffkAvEUVgFtx9A5Vynj"))
            list.add(LatestStickerModel(160, "https://drive.google.com/uc?export=download&id=1GI0-ZG-iigiriWAt7e8JetUkfB9h3z2C"))
            list.add(LatestStickerModel(161, "https://drive.google.com/uc?export=download&id=109ruks0wSYnCi4yiVcYG1VSuEEiPR4jN"))
            list.add(LatestStickerModel(162, "https://drive.google.com/uc?export=download&id=1rLbuV_OFo8zWBkfWtOnArs1cpuwp8LzT"))
            list.add(LatestStickerModel(163, "https://drive.google.com/uc?export=download&id=1GYswEKh8wec0t9Xm-kXkC_28PpXZOYm4"))
            list.add(LatestStickerModel(164, "https://drive.google.com/uc?export=download&id=1ObI_491HFGi6ELK6Tg6eq22ma2sTE5wX"))
            list.add(LatestStickerModel(165, "https://drive.google.com/uc?export=download&id=1bRekHlDYs778YQ1BQPhJQa5jwKYw3qKb"))
            list.add(LatestStickerModel(166, "https://drive.google.com/uc?export=download&id=1JlxhZd7WV7jz8ofSIIUMwo5ikzam88NO"))
            list.add(LatestStickerModel(167, "https://drive.google.com/uc?export=download&id=1lxjVbIL5XW50nPdoPis1-r3caRSh8pvH"))
            list.add(LatestStickerModel(168, "https://drive.google.com/uc?export=download&id=1xM-1-Mc0xdjRlZ319dOd3sg9WCmCHBrj"))
            list.add(LatestStickerModel(169, "https://drive.google.com/uc?export=download&id=1S5a2-nZH3_MrXFkw5kSJiEUYbz5NunvS"))
            list.add(LatestStickerModel(170, "https://drive.google.com/uc?export=download&id=1aOuugx6Z5qqVek48QCfp-JRDb32BR16K"))
            list.add(LatestStickerModel(171, "https://drive.google.com/uc?export=download&id=1KqiZ4Cl0zYag94JjQW5-4vhV6hm7jtCp"))
            list.add(LatestStickerModel(172, "https://drive.google.com/uc?export=download&id=1aLy8nH8UsgV0OlYO8dTicONaa67TbR6h"))
            list.add(LatestStickerModel(173, "https://drive.google.com/uc?export=download&id=1RvCCseQOnEOXiywwwKrj3uEHCRovM2gf"))
            list.add(LatestStickerModel(174, "https://drive.google.com/uc?export=download&id=1iwhcYD7yR3JMjSoz5AGr2wLJk6j6rpdY"))
            list.add(LatestStickerModel(175, "https://drive.google.com/uc?export=download&id=1s0UEZPK3NiQlLDtOBFq1yHKoot5KyoZ5"))
            list.add(LatestStickerModel(176, "https://drive.google.com/uc?export=download&id=1LtCxCKVUpGno41NTFGf3MlpOUGg6m-4D"))
            list.add(LatestStickerModel(177, "https://drive.google.com/uc?export=download&id=1WyGwRDJ_uzFTo9t-k6wT4B1dIsvx0yi6"))
            list.add(LatestStickerModel(178, "https://drive.google.com/uc?export=download&id=1y-F6x8FonxAPVq_KKVA6gSjaOgecX1Mz"))
            list.add(LatestStickerModel(179, "https://drive.google.com/uc?export=download&id=1iMgOfnpQ33hv5cE-yam5xfsk4MBL5JEO"))
            list.add(LatestStickerModel(180, "https://drive.google.com/uc?export=download&id=1R30nc3tuePuSMRiNrql5SCZPOxczgpt1"))
            return list
        }


        fun fillStickersListSeven(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(181, "https://drive.google.com/uc?export=download&id=1de6-8tjcWDCBqP5C2LjYRvUpby_XIGpF"))
            list.add(LatestStickerModel(182, "https://drive.google.com/uc?export=download&id=1w-i1UzOgL04zR657r9NcoHQEbhzILgLB"))
            list.add(LatestStickerModel(183, "https://drive.google.com/uc?export=download&id=1BYs1nos_bEpSJkk45swMvHS-5GpS1b5H"))
            list.add(LatestStickerModel(184, "https://drive.google.com/uc?export=download&id=1ZbQViMkMCmwARZ4sIJePcC1IugMpzPdh"))
            list.add(LatestStickerModel(185, "https://drive.google.com/uc?export=download&id=13JBUUlY7UCiLd-Tt2XGzfufqiHTHsJR3"))
            list.add(LatestStickerModel(186, "https://drive.google.com/uc?export=download&id=1vSFl8hKIsaWe4d_jhj1Y2ILPxurZ39W1"))
            list.add(LatestStickerModel(187, "https://drive.google.com/uc?export=download&id=1gepEjVa4qnD-6qd2BKIFMs1Oqz4LVBRP"))
            list.add(LatestStickerModel(188, "https://drive.google.com/uc?export=download&id=1Ox_XZ5yaxKDKOh77o0ZcsNPdAep1lx2_"))
            list.add(LatestStickerModel(189, "https://drive.google.com/uc?export=download&id=1X9Nv1Z3lGYsXpREz5JeUm_FA809V1MeE"))
            list.add(LatestStickerModel(190, "https://drive.google.com/uc?export=download&id=1npLGQNwP7Z_q6qVStQT4x4J7I4MPwf2V"))
            list.add(LatestStickerModel(191, "https://drive.google.com/uc?export=download&id=1oJs2sKKpESJZ77bqZKTvGebX8Hm9NKx2"))
            list.add(LatestStickerModel(192, "https://drive.google.com/uc?export=download&id=1wApsml3ggPfBfjHWmlPFC91tLzdDCVJJ"))
            list.add(LatestStickerModel(193, "https://drive.google.com/uc?export=download&id=1c5rTZ17IsNL9FGufT2VXvqSVZJMKNtL5"))
            list.add(LatestStickerModel(194, "https://drive.google.com/uc?export=download&id=1AzQ2n2a7tDag_fbekPvhZi1vr0lje9HN"))
            list.add(LatestStickerModel(195, "https://drive.google.com/uc?export=download&id=1HS2HFBiLpoSFwrrrQcT-b6qZUMDbG9g_"))
            list.add(LatestStickerModel(196, "https://drive.google.com/uc?export=download&id=1eFX3A5l74Wbn7eW24sAjy2clsea7GCrH"))
            list.add(LatestStickerModel(197, "https://drive.google.com/uc?export=download&id=1WJU63memh7yud3rq5It1DUcEThFPZ2-i"))
            list.add(LatestStickerModel(198, "https://drive.google.com/uc?export=download&id=1LHUFCj24Y0bqxQBdqVguQPsCc2C7M1ek"))
            list.add(LatestStickerModel(199, "https://drive.google.com/uc?export=download&id=1-kZSXBsdKWYDV8FiGk0a38DMqAO9ODOR"))
            list.add(LatestStickerModel(200, "https://drive.google.com/uc?export=download&id=1u9A9smXSMDczrrSroVpj7sxT0zY1qyde"))
            list.add(LatestStickerModel(201, "https://drive.google.com/uc?export=download&id=1I_B_fntr76xfTMO90ZFTUCmsf28Jwz2h"))
            list.add(LatestStickerModel(202, "https://drive.google.com/uc?export=download&id=1IxAqDc_dXSaHIS4V40CGZ_ZlPMbuvL7j"))
            list.add(LatestStickerModel(203, "https://drive.google.com/uc?export=download&id=13NbAhoW3nb3EQIz6MgWlW94_9y2oNUK1"))
            list.add(LatestStickerModel(204, "https://drive.google.com/uc?export=download&id=1gBMWRVIqIr-2C8baWD6NPSbqlvqnPdHz"))
            list.add(LatestStickerModel(205, "https://drive.google.com/uc?export=download&id=1JFAkFZh02OQfAErB3qxezuszPBZ6nHue"))
            list.add(LatestStickerModel(206, "https://drive.google.com/uc?export=download&id=1Km5nleKGSfbGFwfLs6LwymBrCZOFPBYj"))
            list.add(LatestStickerModel(207, "https://drive.google.com/uc?export=download&id=1npmUuEJw1KVetIqYeVStHglz9BQ-KJrW"))
            list.add(LatestStickerModel(208, "https://drive.google.com/uc?export=download&id=10_YpuOveIokuzCjvcUujLNqsmDq1NgFV"))
            list.add(LatestStickerModel(209, "https://drive.google.com/uc?export=download&id=19A7Z4uI2V53PliZgzyalBs_2ACoJdORl"))
            list.add(LatestStickerModel(210, "https://drive.google.com/uc?export=download&id=1Cw6jQuSWGwn2lyQ0cG_fzu--FbLjDGMy"))
            return list
        }


        fun fillStickersListEight(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(211, "https://drive.google.com/uc?export=download&id=1POVqc5n5oNJMvDE-KwRw7yIv8zZkrSt5"))
            list.add(LatestStickerModel(212, "https://drive.google.com/uc?export=download&id=1ebwLlBU7xivN-vpOLDk7eMeDIBxcKrak"))
            list.add(LatestStickerModel(213, "https://drive.google.com/uc?export=download&id=17Jj0oGNlUw3K6-ar9qEnDIESCxghCDQQ"))
            list.add(LatestStickerModel(214, "https://drive.google.com/uc?export=download&id=19tIFx0WZtuf5J91ykGr7h-atCQWKVgCF"))
            list.add(LatestStickerModel(215, "https://drive.google.com/uc?export=download&id=1gTX8FUmkxQIC_chY5gEQyi25jn3pDr8A"))
            list.add(LatestStickerModel(216, "https://drive.google.com/uc?export=download&id=1aGHn19HiiE1fULZF7dvtlZSArjsMpFJ5"))
            list.add(LatestStickerModel(217, "https://drive.google.com/uc?export=download&id=1_062P7rWU6efmJkUAfqRjGLhpYl9KYJx"))
            list.add(LatestStickerModel(218, "https://drive.google.com/uc?export=download&id=1byF6H7yFvBX4CZJNmHVTCbbPIN_rn4Qt"))
            list.add(LatestStickerModel(219, "https://drive.google.com/uc?export=download&id=1QA9sTZOMBAL47t3a11Ydw_9uCPvheJAg"))
            list.add(LatestStickerModel(220, "https://drive.google.com/uc?export=download&id=1Hnjaxq-4ZAOFJZf-k2VAvF20CQL-t51l"))
            list.add(LatestStickerModel(221, "https://drive.google.com/uc?export=download&id=1AtvUleRSHZ4LSoWbiijTAOdcV9LozWNc"))
            list.add(LatestStickerModel(222, "https://drive.google.com/uc?export=download&id=1bWaUP1sPfFfXZ0BIgZIXWn8y3wuJJSvc"))
            list.add(LatestStickerModel(223, "https://drive.google.com/uc?export=download&id=1RMk0iXIS5cfI2KUwSjh7JKXtpSqKIYnq"))
            list.add(LatestStickerModel(224, "https://drive.google.com/uc?export=download&id=1ncCB5R-pKOb1AKqT2H8iZqvMmpuAob29"))
            list.add(LatestStickerModel(225, "https://drive.google.com/uc?export=download&id=1gFiF2dlHJUjc-95x15blWDI9E3AyhS9K"))
            list.add(LatestStickerModel(226, "https://drive.google.com/uc?export=download&id=1Qd9kRkFpQl2DtLRCll-_SKI8XlHZwbsT"))
            list.add(LatestStickerModel(227, "https://drive.google.com/uc?export=download&id=1RO5GLGBTFl6hzSF3hMAywhwGRJkLeqxA"))
            list.add(LatestStickerModel(228, "https://drive.google.com/uc?export=download&id=15orIJVr8X-wTCjqpGA_4HQ2f-bh08wke"))
            list.add(LatestStickerModel(229, "https://drive.google.com/uc?export=download&id=1_9YL1v82EtkdswTrmefs_JM5NaM_mjfO"))
            list.add(LatestStickerModel(230, "https://drive.google.com/uc?export=download&id=1ZTaIp020xKabD7l1SlSEWtzjLzZSBUaB"))
            list.add(LatestStickerModel(231, "https://drive.google.com/uc?export=download&id=1mTOdLlICyVLG8kBRhEFlSMFON-5c6Dae"))
            list.add(LatestStickerModel(232, "https://drive.google.com/uc?export=download&id=103Ebu6PN56pt17kmCqDorAS11lyA6D6J"))
            list.add(LatestStickerModel(233, "https://drive.google.com/uc?export=download&id=1Q9wSfu5tgfv-81_9lig8YXzQCBhqxF0n"))
            list.add(LatestStickerModel(234, "https://drive.google.com/uc?export=download&id=1v1FASSF7P6NuU8bnlj8LFubp1ci7-cAG"))
            list.add(LatestStickerModel(235, "https://drive.google.com/uc?export=download&id=1aGT-pKLPLvnwoJ2vQCQZuy3dXz4nXJ69"))
            list.add(LatestStickerModel(236, "https://drive.google.com/uc?export=download&id=1bGf4-6m6K-tnM2o4Zco0lwX_gV2giXsz"))
            list.add(LatestStickerModel(237, "https://drive.google.com/uc?export=download&id=1pkUnNFff1GsakEzDMDycBNj_fW4v3uTD"))
            list.add(LatestStickerModel(238, "https://drive.google.com/uc?export=download&id=1fUxmMlv-lfbOTz03lAuzmlI9ENMvDP6Y"))
            list.add(LatestStickerModel(239, "https://drive.google.com/uc?export=download&id=1Q8_9PTLJ_qEK0t0EK9uMn-cDwkp2GFPW"))
            list.add(LatestStickerModel(240, "https://drive.google.com/uc?export=download&id=1EneyFW7CxlY7zMpwwbLs8HxRKbvlsys5"))
            return list
        }


        fun fillStickersListNine(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(241, "https://drive.google.com/uc?export=download&id=1Q6u2A57xbIasIC21bzj2x2lOwRie8Xq0"))
            list.add(LatestStickerModel(242, "https://drive.google.com/uc?export=download&id=1TSC5nV81NSzm0WV3cjFKX4vjNDgY4dVp"))
            list.add(LatestStickerModel(243, "https://drive.google.com/uc?export=download&id=1QaTNVMf2Nko9LC-7gLthboI0Yv98wGJR"))
            list.add(LatestStickerModel(244, "https://drive.google.com/uc?export=download&id=1CeirhjhWbC3BmQ22lvoYSk0EK8A2kYJQ"))
            list.add(LatestStickerModel(245, "https://drive.google.com/uc?export=download&id=1E35feLZtGj8D3uOQFggYfZ1Clio5f22y"))
            list.add(LatestStickerModel(246, "https://drive.google.com/uc?export=download&id=1oZWOWvAe_hFDI40sfreXpOx9dOz9bIyd"))
            list.add(LatestStickerModel(247, "https://drive.google.com/uc?export=download&id=1wc0gBUSClq64paYNQOIUhnyDfT3rvcQf"))
            list.add(LatestStickerModel(248, "https://drive.google.com/uc?export=download&id=1w_Pe1Dk78HgNbukKTtRFwoD8Hg3iAUlu"))
            list.add(LatestStickerModel(249, "https://drive.google.com/uc?export=download&id=12zb63a8nJyjK3TPV_eEXHFYeKK54iXCB"))
            list.add(LatestStickerModel(250, "https://drive.google.com/uc?export=download&id=18-soxhiyG7PondgQa1Yo3jS9xvY_p85p"))
            list.add(LatestStickerModel(251, "https://drive.google.com/uc?export=download&id=1gg5q7PmsurlJop8hDaxRNZ-5Tya8KNde"))
            list.add(LatestStickerModel(252, "https://drive.google.com/uc?export=download&id=1BBaKxhEzZUTARXj-q9J7LfsYrrF6dhg1"))
            list.add(LatestStickerModel(253, "https://drive.google.com/uc?export=download&id=1kpE7FBoPPmdRQRPdlT0MCWg1Y5SWZtL3"))
            list.add(LatestStickerModel(254, "https://drive.google.com/uc?export=download&id=15VX5GlmGc8btUT5ydXmWZITA0Uju06dy"))
            list.add(LatestStickerModel(255, "https://drive.google.com/uc?export=download&id=1u1YvrJf8dCmYWqbOyIjeluFDV_izgFPA"))
            list.add(LatestStickerModel(256, "https://drive.google.com/uc?export=download&id=1JHgWgq3Dqivp0jMyJV05eBS046FVM-UN"))
            list.add(LatestStickerModel(257, "https://drive.google.com/uc?export=download&id=1p1vw5m7OFiLYmNrpHb1_-kJqhi6LN-XA"))
            list.add(LatestStickerModel(258, "https://drive.google.com/uc?export=download&id=1Yi2KRwQ-30x5A-qHfDNeo5_yBN-fIHyW"))
            list.add(LatestStickerModel(259, "https://drive.google.com/uc?export=download&id=1dbcLQvxaXWG00w4lssKTP8TPJSGVm2FF"))
            list.add(LatestStickerModel(260, "https://drive.google.com/uc?export=download&id=1ilQoNGuOLLCkz3jlDXoIyMjcmg_314ul"))
            list.add(LatestStickerModel(261, "https://drive.google.com/uc?export=download&id=1lWkhT73LzKS-qlxL4CpgIgoUp-fGSmar"))
            list.add(LatestStickerModel(262, "https://drive.google.com/uc?export=download&id=1mnKB_qOSPBswWSmCnfhqS93p1xQGvV9i"))
            list.add(LatestStickerModel(263, "https://drive.google.com/uc?export=download&id=17_gMX_6CHWw3vzc-_1fg7VcRNp9Jva7B"))
            list.add(LatestStickerModel(264, "https://drive.google.com/uc?export=download&id=1VyG5WDN0MRgSpp9-nEtBeMEUJbluLMS7"))
            list.add(LatestStickerModel(265, "https://drive.google.com/uc?export=download&id=1ZBOB_TnyeBXG6GVcBzRRZeUgQP1QXZUI"))
            list.add(LatestStickerModel(266, "https://drive.google.com/uc?export=download&id=11rBSfc8zhxLdGNvjUYC7tpY9scuduAb-"))
            list.add(LatestStickerModel(267, "https://drive.google.com/uc?export=download&id=14HAKGPFWwMIAtAKAP7cFtMuX9RDQBfO7"))
            list.add(LatestStickerModel(268, "https://drive.google.com/uc?export=download&id=1J3fwLWK9ux5ckTITEWFq-fCw9DgscKQd"))
            list.add(LatestStickerModel(269, "https://drive.google.com/uc?export=download&id=1Tf5ixP_Br9_4TT2zUtrUJFWjxYEKWKgy"))
            list.add(LatestStickerModel(270, "https://drive.google.com/uc?export=download&id=1unzkNEJab9kMdtwb5pVCVOMl0ga0aK3i"))
            return list
        }


        fun fillStickersListTen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(271, "https://drive.google.com/uc?export=download&id=1JMNgZQ36jHZKkSTZ6ENi4BXgbxh6UY_s"))
            list.add(LatestStickerModel(272, "https://drive.google.com/uc?export=download&id=1A5BAsmgDBhcJb8i4lGA58R3Poivx02Ad"))
            list.add(LatestStickerModel(273, "https://drive.google.com/uc?export=download&id=1R2Y_Yz-oCYKI3tgh3IUo9XMb5DnMqtuB"))
            list.add(LatestStickerModel(274, "https://drive.google.com/uc?export=download&id=1P406JQxOOxng6UKTpCoQO1b8k4LJAmMZ"))
            list.add(LatestStickerModel(275, "https://drive.google.com/uc?export=download&id=171JkUmMRtLly2drYNgyBNKDZsLhgSwru"))
            list.add(LatestStickerModel(276, "https://drive.google.com/uc?export=download&id=1awUNg5lInaUu-LIxUaO2l3dUS2MgEWe2"))
            list.add(LatestStickerModel(277, "https://drive.google.com/uc?export=download&id=1Wm8KlvvDh6OWE_7pjNIVWhvtPIc08Mhr"))
            list.add(LatestStickerModel(278, "https://drive.google.com/uc?export=download&id=1a7rvJLK-a6-ZK8vETnLFt8Zxbs5lMST-"))
            list.add(LatestStickerModel(279, "https://drive.google.com/uc?export=download&id=1l-VtM0afrU1ISqeL6kelp4vbvrhUcjcP"))
            list.add(LatestStickerModel(280, "https://drive.google.com/uc?export=download&id=1X1US8Rvmd9QD3bYr4_ASnxGofqyQBc43"))
            list.add(LatestStickerModel(281, "https://drive.google.com/uc?export=download&id=1w-RcCUAGQ1ywXijDhkFjus1yyJZ8TKag"))
            list.add(LatestStickerModel(282, "https://drive.google.com/uc?export=download&id=1LT4yTW-wKcM0mL4E5gvFzrA8mewHBx7x"))
            list.add(LatestStickerModel(283, "https://drive.google.com/uc?export=download&id=118pGnzV3ryJU7mFdlBax_oZ9fC5BNS3k"))
            list.add(LatestStickerModel(284, "https://drive.google.com/uc?export=download&id=1z-F1K-dwXMogprGbpYR0Nx_ARV7SZrXi"))
            list.add(LatestStickerModel(285, "https://drive.google.com/uc?export=download&id=1_zfUbnsWjb4eVXM0S5CT3yYVY_naXvQe"))
            list.add(LatestStickerModel(286, "https://drive.google.com/uc?export=download&id=16Z67ERl13fxY4iU1ZZT9ar5dWSAfuzG5"))
            list.add(LatestStickerModel(287, "https://drive.google.com/uc?export=download&id=1CPbLDJ57fO1bq4PVt1iB0rmQBBhXDd0C"))
            list.add(LatestStickerModel(288, "https://drive.google.com/uc?export=download&id=1MWMNjAyIfETlWf025KNd-4h644q_MrPa"))
            list.add(LatestStickerModel(289, "https://drive.google.com/uc?export=download&id=1tcyNLwsyq1fGBNUcQYDLTUByVEGTsFqy"))
            list.add(LatestStickerModel(290, "https://drive.google.com/uc?export=download&id=19f3ztN0gfkrkXGqQcObltwb3XCO9evVp"))
            list.add(LatestStickerModel(291, "https://drive.google.com/uc?export=download&id=1s0ShpzdsXv7eMhodLUqtqMjNViIo08tD"))
            list.add(LatestStickerModel(292, "https://drive.google.com/uc?export=download&id=1jmDdK_-xT4z6GvZhaWQq1nJyTKuFg9jt"))
            list.add(LatestStickerModel(293, "https://drive.google.com/uc?export=download&id=1eZ_iZZQjh4JBineaA7HRcU2J_MKJglHi"))
            list.add(LatestStickerModel(294, "https://drive.google.com/uc?export=download&id=1W9LU4FrUAZFHxQQ6cFMy8C7i9css5fqM"))
            list.add(LatestStickerModel(295, "https://drive.google.com/uc?export=download&id=18uebM76kRXXhQwAo75admIgcuBHOcCBB"))
            list.add(LatestStickerModel(296, "https://drive.google.com/uc?export=download&id=1j94GiHb-vHvpzR4IYmaqkKonqSxsJFgo"))
            list.add(LatestStickerModel(297, "https://drive.google.com/uc?export=download&id=1yyP7SzErhw1xaWT98Gf_GMTanQHx1wEx"))
            list.add(LatestStickerModel(298, "https://drive.google.com/uc?export=download&id=1Hm8Br78TYWVl94i9pqGMxRZXIAops_cQ"))
            list.add(LatestStickerModel(299, "https://drive.google.com/uc?export=download&id=1F97SomPUAg1PqwLl04w7cKjR-SRLWZpP"))
            list.add(LatestStickerModel(300, "https://drive.google.com/uc?export=download&id=18CMG_fbbZcClF5HX-Df_aF6xZDhvwOXv"))
            return list
        }


        fun fillStickersListEleven(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(1111, "https://drive.google.com/uc?export=download&id=1EHgyG-ABIK82SrTmiiW7jG4OtlD-cwYU"))
            list.add(LatestStickerModel(2111, "https://drive.google.com/uc?export=download&id=1LSZbA3-kuGB0VHFbVXxFHzACOxrATZlc"))
            list.add(LatestStickerModel(3111, "https://drive.google.com/uc?export=download&id=1TWJG5uOqEW_ml-GjKOUca4DlLXla3Q7h"))
            list.add(LatestStickerModel(4111, "https://drive.google.com/uc?export=download&id=1OXauFeNAvgL7KAGyTmb_r8N849xY9Ssd"))
            list.add(LatestStickerModel(5111, "https://drive.google.com/uc?export=download&id=1-ciRLC1HOlq4_UYFA03fSBejYcxJB2ao"))
            list.add(LatestStickerModel(6111, "https://drive.google.com/uc?export=download&id=1OLFH3kI0bpli0Hwm9sEPgw8VNZZlYOvd"))
            list.add(LatestStickerModel(7111, "https://drive.google.com/uc?export=download&id=1G21W8XtuEGwTFiaYrbVmaeG9glZnFPiS"))
            list.add(LatestStickerModel(8111, "https://drive.google.com/uc?export=download&id=1RWD9nqrDQXmQNKAGkYF2OTSWgQzNv4ZE"))
            list.add(LatestStickerModel(9111, "https://drive.google.com/uc?export=download&id=1kjAOoRUwZhumMMn-r1j7xwbSQKok6cIw"))
            list.add(LatestStickerModel(10111, "https://drive.google.com/uc?export=download&id=1Ou-8mUiTHcZVTyHyyE4TA5bHcFbhzdjc"))
            list.add(LatestStickerModel(11111, "https://drive.google.com/uc?export=download&id=1yReF8Hcgg8W-ClJ7LJquWFmcMHbvlu7f"))
            list.add(LatestStickerModel(12111, "https://drive.google.com/uc?export=download&id=1wHDEHQFqLLob5OFQ3kyg5UQoOC6o6z8I"))
            list.add(LatestStickerModel(13111, "https://drive.google.com/uc?export=download&id=17JLDC2tcmk7dcprHmZwTIq1lwadfyWMO"))
            list.add(LatestStickerModel(14111, "https://drive.google.com/uc?export=download&id=1fXrGTWfqgIqT50rNF6VDQqJWp0TmpjKG"))
            list.add(LatestStickerModel(15111, "https://drive.google.com/uc?export=download&id=1BIhhe3uZAT3yd8laFq6eWh-CcSsmSsmE"))
            list.add(LatestStickerModel(16111, "https://drive.google.com/uc?export=download&id=1PPoq7Sbd7J02gYTarrSKHbA3p5Uw_LrN"))
            list.add(LatestStickerModel(17111, "https://drive.google.com/uc?export=download&id=1_5BjK3MrgLSoRy20Jg8U9bdelQI2FtpJ"))
            list.add(LatestStickerModel(18111, "https://drive.google.com/uc?export=download&id=1ZWzQUKjtak_y965FMbms-1C6bssymEup"))
            list.add(LatestStickerModel(19111, "https://drive.google.com/uc?export=download&id=1C7yf704Q3JMooV8rA3cqBV9kGR6g--NK"))
            list.add(LatestStickerModel(20111, "https://drive.google.com/uc?export=download&id=12fq7Xrqzs1umGUZ1E5-sQrenpj0dp8s2"))
            list.add(LatestStickerModel(21111, "https://drive.google.com/uc?export=download&id=1SsFDpueFdBn6I6YJ_L6-ep9aq73sAEuf"))
            list.add(LatestStickerModel(22111, "https://drive.google.com/uc?export=download&id=1P53WAIgNiEDhguefJKv2QRvmJhAfmzp6"))
            list.add(LatestStickerModel(23111, "https://drive.google.com/uc?export=download&id=1lB3roeen-kS2auN6KsH4GTdqz8Ieehpz"))
            list.add(LatestStickerModel(24111, "https://drive.google.com/uc?export=download&id=1xXKEMoHhn6IxZ1Izok1iBKRiaFXP791t"))
            list.add(LatestStickerModel(25111, "https://drive.google.com/uc?export=download&id=1_EUAUBhq0qidmGlXjodLnUNkibCPnqJY"))
            list.add(LatestStickerModel(26111, "https://drive.google.com/uc?export=download&id=1_g0w1LzcrrM5_JjzzcKVEIwa3ifDmygB"))
            list.add(LatestStickerModel(27111, "https://drive.google.com/uc?export=download&id=1UJTVNPBxnP9SmT0jwomNFL2BunHgTC35"))
            list.add(LatestStickerModel(28111, "https://drive.google.com/uc?export=download&id=1kxk8VHC16MdFIVT0UgN6rH6gv_8A2tBn"))
            list.add(LatestStickerModel(29111, "https://drive.google.com/uc?export=download&id=1uuMEgELkqQk9URUYk7VZ4iFiXsL2Qm8F"))
            list.add(LatestStickerModel(30111, "https://drive.google.com/uc?export=download&id=1GyccQhGn_N4Lzed-w6HHh2S5tfudpAJx"))
            return list
        }


        fun fillStickersListTwelve(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(31111, "https://drive.google.com/uc?export=download&id=1tTKT2wP6ho21EEKmEjuoxg90uWyTfJA6"))
            list.add(LatestStickerModel(32111, "https://drive.google.com/uc?export=download&id=1kg7R_zjUgJKpA4fkYzhDPhfZAwEHdosq"))
            list.add(LatestStickerModel(33111, "https://drive.google.com/uc?export=download&id=1ESxg7jvqyLfxu6Nf3TTFvYcUafCASRVs"))
            list.add(LatestStickerModel(34111, "https://drive.google.com/uc?export=download&id=1NM44ZL3MxJGRnirR5NMJRNztzqtDbBUk"))
            list.add(LatestStickerModel(35111, "https://drive.google.com/uc?export=download&id=16J_hG4HeGvYtzI5Qm3MU96xUxCZ67RUy"))
            list.add(LatestStickerModel(36111, "https://drive.google.com/uc?export=download&id=1TkyMUAHhzTaX5edX1NtW0CcgRz4Cre_7"))
            list.add(LatestStickerModel(37111, "https://drive.google.com/uc?export=download&id=1FrRmwlFObWHsJVVzLMnx2iSDiGJVjNCE"))
            list.add(LatestStickerModel(38111, "https://drive.google.com/uc?export=download&id=1ltrlXli9JKwEH2hfpmsl0nJztbYqqxjV"))
            list.add(LatestStickerModel(39111, "https://drive.google.com/uc?export=download&id=1IBpSJ1LIT4Yq02uowPL8N9Dhh3nUq1T5"))
            list.add(LatestStickerModel(40111, "https://drive.google.com/uc?export=download&id=1JK_K6aDrG52mbguZwMxBy3tP3gTAUvH5"))
            list.add(LatestStickerModel(41111, "https://drive.google.com/uc?export=download&id=1NX9Qeuz_tZuYGrbX4Lh8Dg7PkJ7GqhlA"))
            list.add(LatestStickerModel(42111, "https://drive.google.com/uc?export=download&id=1Xk9LOXFsKfeleskTZPaSm3bsS7BjGcp_"))
            list.add(LatestStickerModel(43111, "https://drive.google.com/uc?export=download&id=1eA5t7W57FNYLaq0QZc8u0Y8KbhT5L1Iy"))
            list.add(LatestStickerModel(44111, "https://drive.google.com/uc?export=download&id=1fwhA2aLDOOYkv4k3kU0AkZHgWJPEt9CR"))
            list.add(LatestStickerModel(45111, "https://drive.google.com/uc?export=download&id=11pPHcmefNAWNk-dk7vB0Wnm-E09bQ6vb"))
            list.add(LatestStickerModel(46111, "https://drive.google.com/uc?export=download&id=1mMNchAzpJuActdfouMnZhr3Nis6-IGDn"))
            list.add(LatestStickerModel(47111, "https://drive.google.com/uc?export=download&id=1CbpHRCvhq_gUcKnSdRjAWjzisrEBG-OY"))
            list.add(LatestStickerModel(48111, "https://drive.google.com/uc?export=download&id=1o8q77CXZppOOUbwFdhDJ1F5nzqq0GYeH"))
            list.add(LatestStickerModel(49111, "https://drive.google.com/uc?export=download&id=1lQz5I3eg2wPfIrmrIiarAwS3ZDzrtYqP"))
            list.add(LatestStickerModel(50111, "https://drive.google.com/uc?export=download&id=102HHioGIBu54bjT9cNMx1DEtRIafvib4"))
            list.add(LatestStickerModel(51111, "https://drive.google.com/uc?export=download&id=1ABSaN6al2aVBtl33Bdd0j91EM4L2f0f0"))
            list.add(LatestStickerModel(52111, "https://drive.google.com/uc?export=download&id=1tJSrWfJAzFkJGUOR2hTHe9ml_VI0Pqpi"))
            list.add(LatestStickerModel(53111, "https://drive.google.com/uc?export=download&id=18b5sWHiBKSmduwnurJLR-3BnTdXZnd5m"))
            list.add(LatestStickerModel(54111, "https://drive.google.com/uc?export=download&id=1z1OkXJC7HBgssFklUOXC7FP6ig-dxbjy"))
            list.add(LatestStickerModel(55111, "https://drive.google.com/uc?export=download&id=1nG_lwzSY8-CbujsPJPMkGMkk31LTkzed"))
            list.add(LatestStickerModel(56111, "https://drive.google.com/uc?export=download&id=1Dosxra_t_sBOzRdanyGbOca8yDr4BSzp"))
            list.add(LatestStickerModel(57111, "https://drive.google.com/uc?export=download&id=1h6LGADEr_Xh0eNxEpsDtJxJIGDqHjVBH"))
            list.add(LatestStickerModel(58111, "https://drive.google.com/uc?export=download&id=1SQxR6lfl4GX5PNtJaVqYhl2GplqkKlHr"))
            list.add(LatestStickerModel(59111, "https://drive.google.com/uc?export=download&id=1vaI7cmuX6R576wQhg5OSVMiBg7pug5uy"))
            list.add(LatestStickerModel(60111, "https://drive.google.com/uc?export=download&id=1QwHdpH06_4IypBKtNkIdPQ3cFQ83K5uV"))
            return list
        }

        fun fillStickersListThirteen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(61111, "https://drive.google.com/uc?export=download&id=1a9dZGZNotjb-d7e_FmgFdVJ498-7jjNX"))
            list.add(LatestStickerModel(62111, "https://drive.google.com/uc?export=download&id=1qb0epkdy18yvoSAO2mNL31PzOI2VvJmT"))
            list.add(LatestStickerModel(63111, "https://drive.google.com/uc?export=download&id=1cMF-71TmstiAMsM7cTMgseCiiugRZpg5"))
            list.add(LatestStickerModel(64111, "https://drive.google.com/uc?export=download&id=1-A0WDuzFZZOR7R43BUEXgMFiQ_dogNt7"))
            list.add(LatestStickerModel(65111, "https://drive.google.com/uc?export=download&id=1q9MNpGYzUI4b1_URIn9lvTCN5gqoI7WC"))
            list.add(LatestStickerModel(66111, "https://drive.google.com/uc?export=download&id=1b9mKR1xTLHpVesq2qyJRCEymO2KXQmMf"))
            list.add(LatestStickerModel(67111, "https://drive.google.com/uc?export=download&id=1kKYuI3N_Vf0mYLGM0W1SLdwWdp9tHGn6"))
            list.add(LatestStickerModel(68111, "https://drive.google.com/uc?export=download&id=1mFS8jt26rlCvr_Hr7EvdVobNgIpD7PQa"))
            list.add(LatestStickerModel(69111, "https://drive.google.com/uc?export=download&id=1NnNGO4vSCIRBypnSEnhMqYp6tOT5bu3H"))
            list.add(LatestStickerModel(70111, "https://drive.google.com/uc?export=download&id=1NLI-x5v1lwWKJU7vsS9rehdMED31BYOR"))
            list.add(LatestStickerModel(71111, "https://drive.google.com/uc?export=download&id=1ENw9mwKiDPIs4fhKLLUroKm1x_RJkyFD"))
            list.add(LatestStickerModel(72111, "https://drive.google.com/uc?export=download&id=18e23SIBSSy7Q7yShl8amr3ZF83t-k4oV"))
            list.add(LatestStickerModel(73111, "https://drive.google.com/uc?export=download&id=1jofTgdCLNSeKS6nWz2WTJ1YIinbFLpEc"))
            list.add(LatestStickerModel(74111, "https://drive.google.com/uc?export=download&id=1IDGUbR9QEEaEJv3z1NyNP1-hztx-lpxD"))
            list.add(LatestStickerModel(75111, "https://drive.google.com/uc?export=download&id=1GTI4wHfRRwMk42ed4aGhwv3FgKDd_km6"))
            list.add(LatestStickerModel(76111, "https://drive.google.com/uc?export=download&id=1BbzO0Xo6s3IGon5pdbIGlyPZodRrFQbq"))
            list.add(LatestStickerModel(77111, "https://drive.google.com/uc?export=download&id=1Mf1jj2uMTtl1Qo2s7FMCn2OqQztk9n8l"))
            list.add(LatestStickerModel(78111, "https://drive.google.com/uc?export=download&id=11VAQjou1FeRS5N5VFCqEnyRBOgHcIq42"))
            list.add(LatestStickerModel(79111, "https://drive.google.com/uc?export=download&id=1YnidI6S5moDg9bcOahJ70wnreGqlCDdo"))
            list.add(LatestStickerModel(80111, "https://drive.google.com/uc?export=download&id=1aBkfv4yCpdTVk_R4U_CXuHmws1piTbqB"))
            list.add(LatestStickerModel(81111, "https://drive.google.com/uc?export=download&id=1Wbyih-xaUdN4v5TLXx8ibPRqWVl_uJ-R"))
            list.add(LatestStickerModel(82111, "https://drive.google.com/uc?export=download&id=13b4kUn6iGw9HaoUd9FokvOibebO5l3XP"))
            list.add(LatestStickerModel(83111, "https://drive.google.com/uc?export=download&id=1gp4TCWb0wEP1L7wgFXYaXs2nMc_CoVGT"))
            list.add(LatestStickerModel(84111, "https://drive.google.com/uc?export=download&id=1m8YogIxRzr6wftmK2QLgWvNVbEAOdLhv"))
            list.add(LatestStickerModel(85111, "https://drive.google.com/uc?export=download&id=194swJzEkNkWIYzDu92azi4B-pO0jhRMc"))
            list.add(LatestStickerModel(86111, "https://drive.google.com/uc?export=download&id=15JtdG8GTZkkAhCC9UZVrIrcrDkUjsUU_"))
            list.add(LatestStickerModel(87111, "https://drive.google.com/uc?export=download&id=1jTGCjKQ56SE-MAUhApSBnE0z9zRwdr_D"))
            list.add(LatestStickerModel(88111, "https://drive.google.com/uc?export=download&id=1UE5KA_vCnFoft4nMVLn46HgxO3bbYaO-"))
            list.add(LatestStickerModel(89111, "https://drive.google.com/uc?export=download&id=1-A7xiYg3IHC7JvENtpE1cdkYxfBYWB5m"))
            list.add(LatestStickerModel(90111, "https://drive.google.com/uc?export=download&id=1UuWCTqbrt2pbrV20YNsSebP61o5dTLYJ"))
            return list
        }


        fun fillStickersListFourteen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(91111, "https://drive.google.com/uc?export=download&id=1uysw21UFc55H12S4LOdRIlv9vP_ZI7wJ"))
            list.add(LatestStickerModel(92111, "https://drive.google.com/uc?export=download&id=1AfC_w7D6jw5LAO1DlyWsI5XQPoQG4XhE"))
            list.add(LatestStickerModel(93111, "https://drive.google.com/uc?export=download&id=151hLgm8YHLove3sPLKdkPd1AHTwb_IAu"))
            list.add(LatestStickerModel(94111, "https://drive.google.com/uc?export=download&id=1fpPH8ryElEPwPLdTUbHMkBuXFSdgjcz0"))
            list.add(LatestStickerModel(95111, "https://drive.google.com/uc?export=download&id=1MrEWMisACrInWouxRu4UNmcwEZvclfoI"))
            list.add(LatestStickerModel(96111, "https://drive.google.com/uc?export=download&id=12XiiYdT3_tMwbsUsLqHUchJiEPpjaG8k"))
            list.add(LatestStickerModel(97111, "https://drive.google.com/uc?export=download&id=11Ep5GBCrcpw8vUp_gQfB_QSAa-xDLOSc"))
            list.add(LatestStickerModel(98111, "https://drive.google.com/uc?export=download&id=1OKT7PBUWMJdEZOXBD9Ac0_3qlG4HB9ol"))
            list.add(LatestStickerModel(99111, "https://drive.google.com/uc?export=download&id=1oMTmmsj_e8AyUS37ngtXgB8JTn6JyXW9"))
            list.add(LatestStickerModel(100111, "https://drive.google.com/uc?export=download&id=1m18awpTVEZr_SmbKxtLwHEv2vyxG_X7r"))
            list.add(LatestStickerModel(101111, "https://drive.google.com/uc?export=download&id=1O6qMPxxC6Sd_Ov13YXakevNRiaOsq0Dm"))
            list.add(LatestStickerModel(102111, "https://drive.google.com/uc?export=download&id=1AbpexUqKCdcsc0ouqOyqsJBVjrmEt2P3"))
            list.add(LatestStickerModel(103111, "https://drive.google.com/uc?export=download&id=1IPPVXL2Olp8NIkT9NsMZjFuNVnHX4n3Y"))
            list.add(LatestStickerModel(104111, "https://drive.google.com/uc?export=download&id=1tyrfIEXFo5wiHaPobamLY2TwcXDdnOjS"))
            list.add(LatestStickerModel(105111, "https://drive.google.com/uc?export=download&id=1BzTDm4Osv2xpSbsw_gMbRyJ5Op0b9p2K"))
            list.add(LatestStickerModel(106111, "https://drive.google.com/uc?export=download&id=1TQj7oTlZdkWl4_4Q8Rjx2acf92ELFYMA"))
            list.add(LatestStickerModel(107111, "https://drive.google.com/uc?export=download&id=1m0t6RzFcm_1OMxeIAmyCPKrXiADPy4N7"))
            list.add(LatestStickerModel(108111, "https://drive.google.com/uc?export=download&id=1_EVmrPqaJdqBwqwNlJedK7gK715ug4Om"))
            list.add(LatestStickerModel(109111, "https://drive.google.com/uc?export=download&id=1ubwQ_0F_nhpYr7gb9gJAbUip2HqyQ0Is"))
            list.add(LatestStickerModel(110111, "https://drive.google.com/uc?export=download&id=1mtb3pM_x0J4Y29DdZuyxEaTKu2-wYQM0"))
            list.add(LatestStickerModel(111111, "https://drive.google.com/uc?export=download&id=1A0DhixlX6wN4Hu3H9vhnOSGwKQWHoIzI"))
            list.add(LatestStickerModel(112111, "https://drive.google.com/uc?export=download&id=1Fydo2Yip5YgbPpU8-csT33b9oa0EHljX"))
            list.add(LatestStickerModel(113111, "https://drive.google.com/uc?export=download&id=1j8L-y6VrliRRb68qoKqYGqDvPY3-iJke"))
            list.add(LatestStickerModel(114111, "https://drive.google.com/uc?export=download&id=15cOWbdoJUz8dvCOOohUY6Gkg3oRtZ5Zv"))
            list.add(LatestStickerModel(115111, "https://drive.google.com/uc?export=download&id=13hA0NRx1-kTn0TOUUBrf0pwKvSGCFAjO"))
            list.add(LatestStickerModel(116111, "https://drive.google.com/uc?export=download&id=1auDmzX1KhLN5aqPgBHSf42USbbqOoIC9"))
            list.add(LatestStickerModel(117111, "https://drive.google.com/uc?export=download&id=1gsQoFuGtfsm68io-x7MY7sw00oTO4Vvc"))
            list.add(LatestStickerModel(118111, "https://drive.google.com/uc?export=download&id=1H67xQ4HJj0y2Oru6TCnyCiTcN4KzjY77"))
            list.add(LatestStickerModel(119111, "https://drive.google.com/uc?export=download&id=1qR1lMoO9jRLVPuaB8gMrLYxoOWET0tqC"))
            list.add(LatestStickerModel(120111, "https://drive.google.com/uc?export=download&id=1VPVvCjyd2ADHT2fkJXFJQeKClQJgrXsS"))
            return list
        }


        fun fillStickersListFifteen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(121111, "https://drive.google.com/uc?export=download&id=153Jg-TPQqZOnewdyPtcmQU4m958RRgEY"))
            list.add(LatestStickerModel(122111, "https://drive.google.com/uc?export=download&id=1aRqP0B_z9mXWfIaqzrgpT4SMwyscjJKl"))
            list.add(LatestStickerModel(123111, "https://drive.google.com/uc?export=download&id=15OUDzcDFphqeQX3LagnKvBGzlrL6wX19"))
            list.add(LatestStickerModel(124111, "https://drive.google.com/uc?export=download&id=1s4IlkvuTENAxNstQwykVbv_cK0uV0PMd"))
            list.add(LatestStickerModel(125111, "https://drive.google.com/uc?export=download&id=1yLpFPPPP_PYLpRSAOpqQ650kEKIE86dD"))
            list.add(LatestStickerModel(126111, "https://drive.google.com/uc?export=download&id=1vgSPF_ybcyn5cfTeBaxxV7r_jL3pPVo9"))
            list.add(LatestStickerModel(127111, "https://drive.google.com/uc?export=download&id=1m5Q4Z1QeQu_jZ1Xxjr78tONG4FE35vJn"))
            list.add(LatestStickerModel(128111, "https://drive.google.com/uc?export=download&id=1_-7thq8m3QO37HBK64jKcDfU6087caDa"))
            list.add(LatestStickerModel(129111, "https://drive.google.com/uc?export=download&id=1jF3h4eccrx4zVA7dGg1g_yHkr-sXw3B7"))
            list.add(LatestStickerModel(130111, "https://drive.google.com/uc?export=download&id=1P0-_bDbqPXA_NyMNCBX8_CEVcIC_n2_A"))
            list.add(LatestStickerModel(131111, "https://drive.google.com/uc?export=download&id=1dHrzmQLzMDCn02QhTVrDTZluXFDnnUO0"))
            list.add(LatestStickerModel(132111, "https://drive.google.com/uc?export=download&id=1ai1gBQuY5v1ly-xxUZo7LVtcY_Vokzhc"))
            list.add(LatestStickerModel(133111, "https://drive.google.com/uc?export=download&id=193XRxOgSO87Gb9OwTqqzMtnBoyCnWU-W"))
            list.add(LatestStickerModel(134111, "https://drive.google.com/uc?export=download&id=127fVz4eJmm0vTpgEP0R2eeWjtuFZ6EYV"))
            list.add(LatestStickerModel(135111, "https://drive.google.com/uc?export=download&id=1_wdJ1hKvrskVpeYoHI6fgLxIrgrZRfUy"))
            list.add(LatestStickerModel(136111, "https://drive.google.com/uc?export=download&id=1jMRP5tQCdBFnQkBS2w5zjAJ5g-D5-FFb"))
            list.add(LatestStickerModel(137111, "https://drive.google.com/uc?export=download&id=1I-R4ZxLEHYseYHzxU6rFLrfpZFHws5i9"))
            list.add(LatestStickerModel(138111, "https://drive.google.com/uc?export=download&id=1UNPTnUn416hdF9FYUcw9QKwa5UYb2GcZ"))
            list.add(LatestStickerModel(139111, "https://drive.google.com/uc?export=download&id=1kUA9945kEjODAVXb-6OHLeb4Lva06Azg"))
            list.add(LatestStickerModel(140111, "https://drive.google.com/uc?export=download&id=11RGSpYS7U2jvxxzowI4WYLzlVqXszRCC"))
            list.add(LatestStickerModel(141111, "https://drive.google.com/uc?export=download&id=1WFf5XdBIoN7OJ7qtYItftXXHjS3JRP4s"))
            list.add(LatestStickerModel(142111, "https://drive.google.com/uc?export=download&id=1kdPP-l7VOd0J3JAa3nwLijRaa-sZ25AQ"))
            list.add(LatestStickerModel(143111, "https://drive.google.com/uc?export=download&id=1ujmIhcwsO6ZFZVdjALJVcB0Z9YHToYN3"))
            list.add(LatestStickerModel(144111, "https://drive.google.com/uc?export=download&id=1kEox2EGhZWf2iN2r5-PK2fiHZ4cJfhAd"))
            list.add(LatestStickerModel(145111, "https://drive.google.com/uc?export=download&id=1DQDiHsYiMacz7vTbGlKePjIVrg-T39ij"))
            list.add(LatestStickerModel(146111, "https://drive.google.com/uc?export=download&id=1xYHGzru5PZkRB39YFQzytnPbNk2ggqHW"))
            list.add(LatestStickerModel(147111, "https://drive.google.com/uc?export=download&id=1gkksHBMt1IOqraktP0v6JeHVgibXFwuv"))
            list.add(LatestStickerModel(148111, "https://drive.google.com/uc?export=download&id=1jHw-FUi-KmYp0Heqsfor7jS3JFn7fjfZ"))
            list.add(LatestStickerModel(149111, "https://drive.google.com/uc?export=download&id=1N9rPu0tIO29xP50w3_6KCG_2OP8RGB63"))
            list.add(LatestStickerModel(150111, "https://drive.google.com/uc?export=download&id=1HsYXvmTfZTFAUPfxV1KmEQ6jwOMpA1vr"))
            return list
        }


        fun fillStickersListSixteen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(151111, "https://drive.google.com/uc?export=download&id=11wUWTRjwqEpbPz3bG_SbDrEl3d3GN_yO"))
            list.add(LatestStickerModel(152111, "https://drive.google.com/uc?export=download&id=1e-T5B9KM5YsDR2_hTQ6YCNvGTF2hq8kv"))
            list.add(LatestStickerModel(153111, "https://drive.google.com/uc?export=download&id=1GOfTsZ1sUf-F2fwqug-mSQOWFP7Cq49v"))
            list.add(LatestStickerModel(154111, "https://drive.google.com/uc?export=download&id=1zzx_cV-XRcljMrQCturVedNwtweaZYI-"))
            list.add(LatestStickerModel(155111, "https://drive.google.com/uc?export=download&id=1XWUDTcfsgRWQK5aLdYdccJYy-pxJscJb"))
            list.add(LatestStickerModel(156111, "https://drive.google.com/uc?export=download&id=17baKCudPQr3hwzCy6JCMEkt_Oq4xJHYo"))
            list.add(LatestStickerModel(157111, "https://drive.google.com/uc?export=download&id=1pzvgkyNW_cKHtooTwdTKAYEFVghFsLXG"))
            list.add(LatestStickerModel(158111, "https://drive.google.com/uc?export=download&id=1S73nWWjfoEBD66eSto-Ru3BNGqGqJnMK"))
            list.add(LatestStickerModel(159111, "https://drive.google.com/uc?export=download&id=1C_4vVky-hMN6922te_geigQiKePORc1I"))
            list.add(LatestStickerModel(160111, "https://drive.google.com/uc?export=download&id=1kkwIctfg28C2wF1Qbl2Q2p1Lc7HtZicO"))
            list.add(LatestStickerModel(161111, "https://drive.google.com/uc?export=download&id=1kHcU3XXyMUEGf39FEJY4f6mxka1WNJtB"))
            list.add(LatestStickerModel(162111, "https://drive.google.com/uc?export=download&id=1T_KwrRXlCwLJDurLBESyvTdANpRVBbN3"))
            list.add(LatestStickerModel(163111, "https://drive.google.com/uc?export=download&id=1pVR3U96SLkFzNTnmXDYGC3c3tO3HMm2E"))
            list.add(LatestStickerModel(164111, "https://drive.google.com/uc?export=download&id=1B-xU4Z3mQJzA-gCGrs-0UQq5bkT9zknB"))
            list.add(LatestStickerModel(165111, "https://drive.google.com/uc?export=download&id=1phdk0dIxFvq8zIAQ5jsHIS6727SKh48s"))
            list.add(LatestStickerModel(166111, "https://drive.google.com/uc?export=download&id=1NEW8zYVOgmeYdUYQlp6sNT2Fho5_GS_N"))
            list.add(LatestStickerModel(167111, "https://drive.google.com/uc?export=download&id=1dt0fU6lshcdIv8mJiEzSD5hGAJ7QU-Du"))
            list.add(LatestStickerModel(168111, "https://drive.google.com/uc?export=download&id=1jwnpKwpg_d_VZGy3ztoIv-PCl9Ay62uC"))
            list.add(LatestStickerModel(169111, "https://drive.google.com/uc?export=download&id=1ED4k31-8C3SQKvQBPlpJKSI_Fbl4Dt-Z"))
            list.add(LatestStickerModel(170111, "https://drive.google.com/uc?export=download&id=1gTHFRMd_8r1j4yVHryhj7NyTCHkdv-8j"))
            list.add(LatestStickerModel(171111, "https://drive.google.com/uc?export=download&id=1076LeYmShtIrw5cCtavRqX8Qu0pbYgsP"))
            list.add(LatestStickerModel(172111, "https://drive.google.com/uc?export=download&id=1pbuFedeTfKZH7CR9Kqow-smD7_-bUwFf"))
            list.add(LatestStickerModel(173111, "https://drive.google.com/uc?export=download&id=1vDzcyJypV_BWbEGrw3e-4360X5yOgDM_"))
            list.add(LatestStickerModel(174111, "https://drive.google.com/uc?export=download&id=1b_0i1PA3JNMqSLfMBttcNWPcyFDhLYj3"))
            list.add(LatestStickerModel(175111, "https://drive.google.com/uc?export=download&id=1TF5cU46yKlLXtOOdoFR73cFUFImx8bPf"))
            list.add(LatestStickerModel(176111, "https://drive.google.com/uc?export=download&id=19TqrxuQxeAWxiurktp2KtAp4Ugri86r7"))
            list.add(LatestStickerModel(177111, "https://drive.google.com/uc?export=download&id=1RufsAsewBmES2tCbrk_ThzDqrU8pb1cC"))
            list.add(LatestStickerModel(178111, "https://drive.google.com/uc?export=download&id=1siWMmAgCS8heIyQrK2kle6-Lmn7jOa-E"))
            list.add(LatestStickerModel(179111, "https://drive.google.com/uc?export=download&id=1y47G6TO-pmu1eBtUx2-H5QfTqHeMEMBX"))
            list.add(LatestStickerModel(180111, "https://drive.google.com/uc?export=download&id=1hiLpfXJNI3VllaKNIfpntQQ25r7Y58OO"))
            return list
        }


        fun fillStickersListSeventeen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(181111, "https://drive.google.com/uc?export=download&id=1hwh5Oj0WZnnZJbWY02aHuAmbBgKne2nr"))
            list.add(LatestStickerModel(182111, "https://drive.google.com/uc?export=download&id=1CLwS32cx2gVqHKyEX4r8MF_HROTR8joc"))
            list.add(LatestStickerModel(183111, "https://drive.google.com/uc?export=download&id=1YUZCEvmLpJOkldzAlwbocbk6wm2jTbIf"))
            list.add(LatestStickerModel(184111, "https://drive.google.com/uc?export=download&id=1QWTfEoi0hV2iycvD5NnkBYK-vemgLEo_"))
            list.add(LatestStickerModel(185111, "https://drive.google.com/uc?export=download&id=1LQnR8xxzMjP213MYrmCUjU-_tcjoBC9_"))
            list.add(LatestStickerModel(186111, "https://drive.google.com/uc?export=download&id=1DaE24z_zqYc8CoyCbytNDisKIoF7xV6D"))
            list.add(LatestStickerModel(187111, "https://drive.google.com/uc?export=download&id=1LNpMjQSosCKFRHzKSg7b8mVYuimWSrsY"))
            list.add(LatestStickerModel(188111, "https://drive.google.com/uc?export=download&id=1m1y_mnsYpHFL7C3xSeOF9XxSvkfwnT_Q"))
            list.add(LatestStickerModel(189111, "https://drive.google.com/uc?export=download&id=1v4yOMIOflqD-_4-Yyc__EBYIEwQB6ltt"))
            list.add(LatestStickerModel(190111, "https://drive.google.com/uc?export=download&id=1JWrNaU6e9NqoTphaWy5842dsZExPiY6r"))
            list.add(LatestStickerModel(191111, "https://drive.google.com/uc?export=download&id=1M088lahf_vhm-zNspDeeL2_xa0nVyFL3"))
            list.add(LatestStickerModel(192111, "https://drive.google.com/uc?export=download&id=1wdj95xFHEwC35s1c1DNC8rXwYKwjMbyS"))
            list.add(LatestStickerModel(193111, "https://drive.google.com/uc?export=download&id=1QlBFZM10rRVlXV5OZVRdnFejQaSVH9_1"))
            list.add(LatestStickerModel(194111, "https://drive.google.com/uc?export=download&id=13uiAi8WMWJo6zwaWDg8RuZbKS1tQeZ-Q"))
            list.add(LatestStickerModel(195111, "https://drive.google.com/uc?export=download&id=1NJC77YSWCossWQcoNt4r5LIbUVjQvC8g"))
            list.add(LatestStickerModel(196111, "https://drive.google.com/uc?export=download&id=1sgRYzGUEdPCKfnZQ9VmKsfgv8soYVaZz"))
            list.add(LatestStickerModel(197111, "https://drive.google.com/uc?export=download&id=1-AaLF0wPAg0WQPKb_KiS_R-Bh1YEDdFq"))
            list.add(LatestStickerModel(198111, "https://drive.google.com/uc?export=download&id=1L5mDfUz1C07ByL38dZi2gVfDu6_D-VyY"))
            list.add(LatestStickerModel(199111, "https://drive.google.com/uc?export=download&id=1BXi1RhRIxb9wPskBYAD2LhheMDO7pYtt"))
            list.add(LatestStickerModel(200111, "https://drive.google.com/uc?export=download&id=1dmiWcoBytcP40GcdJMwhkxwVIVurj9tI"))
            list.add(LatestStickerModel(201111, "https://drive.google.com/uc?export=download&id=1FYaaNpCIkt2zF4Tqi6_SVIxS0y9Uz-RS"))
            list.add(LatestStickerModel(202111, "https://drive.google.com/uc?export=download&id=1KMYn1nC51gUslUqBK0aoPZKNPo3n_4vW"))
            list.add(LatestStickerModel(203111, "https://drive.google.com/uc?export=download&id=1SM4vzZLZt-YKuzP2BqGhRrFapjjPqLiB"))
            list.add(LatestStickerModel(204111, "https://drive.google.com/uc?export=download&id=1o645n8Au7dgzu_UFwKclkJglQJMGpvP_"))
            list.add(LatestStickerModel(205111, "https://drive.google.com/uc?export=download&id=1XxHgS3DwavyPOFDzD46cU9_qOrc5P67h"))
            list.add(LatestStickerModel(206111, "https://drive.google.com/uc?export=download&id=1aUo9IUiarTNYUTnHsEr4AOsrhiV1PgQY"))
            list.add(LatestStickerModel(207111, "https://drive.google.com/uc?export=download&id=1IblriQ-ss-NUUKy0tB5bCkp65rIBo0QR"))
            list.add(LatestStickerModel(208111, "https://drive.google.com/uc?export=download&id=1u7Hct_RQRC2kJAVC1e2oXwUljSVzIrV4"))
            list.add(LatestStickerModel(209111, "https://drive.google.com/uc?export=download&id=1Fh1pdNufaAoT_E90L5SQeQq4UCupOktE"))
            list.add(LatestStickerModel(210111, "https://drive.google.com/uc?export=download&id=1NGKqWMAxYrzzKo_gJP6WtIBl7HIrO5Uy"))
            return list
        }


        fun fillStickersListEighteen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(211111, "https://drive.google.com/uc?export=download&id=1qmTNuVGJx9aWec0CWGICUSlRBk6qJ4ep"))
            list.add(LatestStickerModel(212111, "https://drive.google.com/uc?export=download&id=1s73d_INAgsSoMZDowrMTrj0kUeNNXh1P"))
            list.add(LatestStickerModel(213111, "https://drive.google.com/uc?export=download&id=1sZg7fU6PGdkYgRJd-zT6WzMLhryrn3Ce"))
            list.add(LatestStickerModel(214111, "https://drive.google.com/uc?export=download&id=1nuWuBseoDRm9l8yk0ZTjviZUF30xZL1s"))
            list.add(LatestStickerModel(215111, "https://drive.google.com/uc?export=download&id=1Za-IKtsXzFqgc8wKzNQgP1rePlmyv0yR"))
            list.add(LatestStickerModel(216111, "https://drive.google.com/uc?export=download&id=1qxR5MqxVEzadGi-PG0vppIEDzxaXKhrw"))
            list.add(LatestStickerModel(217111, "https://drive.google.com/uc?export=download&id=1p3AK2ig9CyDM7XuhtPI3rfcpQdnfso99"))
            list.add(LatestStickerModel(218111, "https://drive.google.com/uc?export=download&id=1hhJRbt9fE95T5qcIP8T6pomNaAJOeHer"))
            list.add(LatestStickerModel(219111, "https://drive.google.com/uc?export=download&id=1CKzM2vuCYJKbWThewPFOaXoDAVWXzs6k"))
            list.add(LatestStickerModel(220111, "https://drive.google.com/uc?export=download&id=1-4AsVjvvEqNQr2IxcVsInjU74WW0HbV_"))
            list.add(LatestStickerModel(221111, "https://drive.google.com/uc?export=download&id=11GAX4cwwXRaYRgchFT0DlrkQRUQv2FAi"))
            list.add(LatestStickerModel(222111, "https://drive.google.com/uc?export=download&id=1DdHtEx74WgIuVOfm6Vo89yPOmvvqPP1A"))
            list.add(LatestStickerModel(223111, "https://drive.google.com/uc?export=download&id=1Q9SIwG62bUZMDhH5PnSsbXDt3hoPXkoS"))
            list.add(LatestStickerModel(224111, "https://drive.google.com/uc?export=download&id=14cCKgXc9z9Cc6h1KbuX2AgjwnaZjxNu4"))
            list.add(LatestStickerModel(225111, "https://drive.google.com/uc?export=download&id=1D4h7IfBwvmjokuWqrhObWLk3mZ0NHNx7"))
            list.add(LatestStickerModel(226111, "https://drive.google.com/uc?export=download&id=1HRA_O2DNwBWLMU8ZqWac2132YT6XTo_G"))
            list.add(LatestStickerModel(227111, "https://drive.google.com/uc?export=download&id=1XoTB8fyUpNI_8Jsae2pYEQM1Ym8ZOc0x"))
            list.add(LatestStickerModel(228111, "https://drive.google.com/uc?export=download&id=1YuIdUnRmpoRpIAjHffsk1r8vMjkTD86V"))
            list.add(LatestStickerModel(229111, "https://drive.google.com/uc?export=download&id=13cqgOwNDfyY1aFd93mVIBu2IRV4SpK9S"))
            list.add(LatestStickerModel(230111, "https://drive.google.com/uc?export=download&id=1T3fWrk9A03I15d030-59Y17Fymwt89Xu"))
            list.add(LatestStickerModel(231111, "https://drive.google.com/uc?export=download&id=1xIwTxrEj9dDAhbZc6tTGNl_3L4zYHlZ9"))
            list.add(LatestStickerModel(232111, "https://drive.google.com/uc?export=download&id=1TZH_tPTUfA764k2zImU1NjEIfAZIYSKP"))
            list.add(LatestStickerModel(233111, "https://drive.google.com/uc?export=download&id=1dKYmo4w7lVqEtVFZ39bPgK6vnxlDGz6s"))
            list.add(LatestStickerModel(234111, "https://drive.google.com/uc?export=download&id=1VPurXS2263jJM41VaOtDNXEJlzla9VXS"))
            list.add(LatestStickerModel(235111, "https://drive.google.com/uc?export=download&id=1Dn14CjP6dsNBsmaqu3fgAAmBQdJJLWxE"))
            list.add(LatestStickerModel(236111, "https://drive.google.com/uc?export=download&id=1YN4zPcxumOvnpp_mdseH5FVU1KLI6LWv"))
            list.add(LatestStickerModel(237111, "https://drive.google.com/uc?export=download&id=1X-jqmXHgUrSXDiX8n_nXLtQ3Cug66ciJ"))
            list.add(LatestStickerModel(238111, "https://drive.google.com/uc?export=download&id=1LJYnRCGvmDMHFn1uhFu4ePUJgK95FIlY"))
            list.add(LatestStickerModel(239111, "https://drive.google.com/uc?export=download&id=1OjVyJgYljQaKgX1bXfgKYp4s1kjvCC2g"))
            list.add(LatestStickerModel(240111, "https://drive.google.com/uc?export=download&id=1Pge-kQAxr5iJ-Z2PkFggyCTqh_EzmpRx"))
            return list
        }


        fun fillStickersListNinteen(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(241111, "https://drive.google.com/uc?export=download&id=1TMSJlyhK3Yxb3ATk_m2LPER-DGnm2Euw"))
            list.add(LatestStickerModel(242111, "https://drive.google.com/uc?export=download&id=1U9VUbZHGlFEXDr35FfKJeWk30P7jBFb3"))
            list.add(LatestStickerModel(243111, "https://drive.google.com/uc?export=download&id=1FkrO62OJdcH6jqairFAKwhKsjTXTUsyv"))
            list.add(LatestStickerModel(244111, "https://drive.google.com/uc?export=download&id=1MAP7lXBo4GYbQvO5GqW56-jNANVVDQFG"))
            list.add(LatestStickerModel(245111, "https://drive.google.com/uc?export=download&id=1UPFLHggxs2j0DvLIGpjBBK4N_AZDxrSF"))
            list.add(LatestStickerModel(246111, "https://drive.google.com/uc?export=download&id=19vOYl49p1R1V6as0tvPXPesMmdARVEPs"))
            list.add(LatestStickerModel(247111, "https://drive.google.com/uc?export=download&id=1z5GWSmcWI2qPIYp1_FcDwQcKOD-QshbZ"))
            list.add(LatestStickerModel(248111, "https://drive.google.com/uc?export=download&id=1lgpfnIDj4MNmE9Fi5ttouNhzWiyiPdRk"))
            list.add(LatestStickerModel(249111, "https://drive.google.com/uc?export=download&id=1JY_danz5RgBAoq_cEEXR3iyQqaEZGU1-"))
            list.add(LatestStickerModel(250111, "https://drive.google.com/uc?export=download&id=1tnRMoKibw0UzpSuvVtSE3pVoZd_a_Lpw"))
            list.add(LatestStickerModel(251111, "https://drive.google.com/uc?export=download&id=1KwwdxBjs9l7yhZlxnABVwc1JTHKHS-0T"))
            list.add(LatestStickerModel(252111, "https://drive.google.com/uc?export=download&id=1Hbs9oK5nULO4T0boTSxVHNbfo1XYuSdD"))
            list.add(LatestStickerModel(253111, "https://drive.google.com/uc?export=download&id=1eSXcuNBD9v2zFkR10W82gIUS8CXZamz7"))
            list.add(LatestStickerModel(254111, "https://drive.google.com/uc?export=download&id=1t8_v4xuh6ER1R8FcOlQQyLJ-S-gA5hwY"))
            list.add(LatestStickerModel(255111, "https://drive.google.com/uc?export=download&id=10E2VVbtSDV9oG9LCL_TPjgm3lsHLLzJT"))
            list.add(LatestStickerModel(256111, "https://drive.google.com/uc?export=download&id=1laoIafgRevOZLlGZj9E-wxbgu6px3SSQ"))
            list.add(LatestStickerModel(257111, "https://drive.google.com/uc?export=download&id=1UoOI6_otr1stQzIluH-Mz_JSdmlWZNTr"))
            list.add(LatestStickerModel(258111, "https://drive.google.com/uc?export=download&id=17NswVnFTQtW_ZPT-_OTC5-cyExwtb9_1"))
            list.add(LatestStickerModel(259111, "https://drive.google.com/uc?export=download&id=1g1FGBLm41VUgJOTHfEfHppSW0yy5XSvb"))
            list.add(LatestStickerModel(260111, "https://drive.google.com/uc?export=download&id=135ZDOjCAuZYqqvZh8rCywSl4X5dzEzSi"))
            list.add(LatestStickerModel(261111, "https://drive.google.com/uc?export=download&id=1kMqRMk9CO590gyaniIms0RZIUluey9a3"))
            list.add(LatestStickerModel(262111, "https://drive.google.com/uc?export=download&id=1J_B9oRaCgqBt1ppw-DQQIaRUZh28CzCY"))
            list.add(LatestStickerModel(263111, "https://drive.google.com/uc?export=download&id=17AYhSPmZdEgPdrfB9g9pnOXYhCk1m9It"))
            list.add(LatestStickerModel(264111, "https://drive.google.com/uc?export=download&id=1z4kNQGD8zE-E5DPogkFnNh82SZLcJD0W"))
            list.add(LatestStickerModel(265111, "https://drive.google.com/uc?export=download&id=10oEXX3daKFyNQ3JvMENjVYUkZ9Ll8Cx_"))
            list.add(LatestStickerModel(266111, "https://drive.google.com/uc?export=download&id=1k-vjrbCwlHLaYiGaiqpUGoDqKnso-rQ_"))
            list.add(LatestStickerModel(267111, "https://drive.google.com/uc?export=download&id=1Ks9kyhEXKxedCQwdRckrinY-pnAlWock"))
            list.add(LatestStickerModel(268111, "https://drive.google.com/uc?export=download&id=1mQZPk5sD-Ys61t3zgXMaGHxZBBH_ixpv"))
            list.add(LatestStickerModel(269111, "https://drive.google.com/uc?export=download&id=1Jz58t4EVQrbp7Uhne6mVIJAfbpWckQPR"))
            list.add(LatestStickerModel(270111, "https://drive.google.com/uc?export=download&id=1xOW8uj5KNVgTStMXd6YdB84y5F3QvoKn"))
            return list
        }


        fun fillStickersListTwenty(): ArrayList<LatestStickerModel> {
            val list = ArrayList<LatestStickerModel>()
            list.add(LatestStickerModel(271111, "https://drive.google.com/uc?export=download&id=1tss32q0rnzxiAkg9_O9UEsjUwDKpIV0h"))
            list.add(LatestStickerModel(272111, "https://drive.google.com/uc?export=download&id=1y5CGrEcyIlxYMeu-ye10ywN0mOERjjI2"))
            list.add(LatestStickerModel(273111, "https://drive.google.com/uc?export=download&id=1orOuzxgDpLNK5z3N3Qx-UfixRYJ2UMIl"))
            list.add(LatestStickerModel(274111, "https://drive.google.com/uc?export=download&id=1i5hPb7NPShHMF_wW53EVfaBVZJWcOg89"))
            list.add(LatestStickerModel(275111, "https://drive.google.com/uc?export=download&id=1TqUyRfrNusWqZKguuIiXIHfE-j-Q32W3"))
            list.add(LatestStickerModel(276111, "https://drive.google.com/uc?export=download&id=1tv8oHfIH8lSjDxJaIwNopsbTkh0UkTlW"))
            list.add(LatestStickerModel(277111, "https://drive.google.com/uc?export=download&id=1PRqWVeQUg0XhAG8p3QTt7MfxCbyBNhOo"))
            list.add(LatestStickerModel(278111, "https://drive.google.com/uc?export=download&id=1V1HOzDI_M-ip46aJ5IW8wnxLOhFwcp1G"))
            list.add(LatestStickerModel(279111, "https://drive.google.com/uc?export=download&id=1D8lLQKYsEBO9C945KePKP6GE4Z3vJuZt"))
            list.add(LatestStickerModel(280111, "https://drive.google.com/uc?export=download&id=1EN7eMpvp3Mjx91O8wn3Ld2tJLpjn1yUa"))
            list.add(LatestStickerModel(281111, "https://drive.google.com/uc?export=download&id=1y4AHbUYQ2F7OFYnvzEjiGoFUYxCtar1l"))
            list.add(LatestStickerModel(282111, "https://drive.google.com/uc?export=download&id=1hcezSGnODNQG-VxY3dTbubhBlhMg8mF0"))
            list.add(LatestStickerModel(283111, "https://drive.google.com/uc?export=download&id=1GS-lo93oMgh--VGGcbBGVE2gWAKB5AV3"))
            list.add(LatestStickerModel(284111, "https://drive.google.com/uc?export=download&id=12ssfXiJirH3RqxtpYdBaaDeK3SKaGUJy"))
            list.add(LatestStickerModel(285111, "https://drive.google.com/uc?export=download&id=1poOz-D8R87AaEUagdR_bI1xBatFdRmKn"))
            list.add(LatestStickerModel(286111, "https://drive.google.com/uc?export=download&id=1U1E6-8pAOBSYnhQOxdAfPPBLtK10nWHE"))
            list.add(LatestStickerModel(287111, "https://drive.google.com/uc?export=download&id=1qt2V0k0L3JbBR4hotESshAfzPmcv6Sb1"))
            list.add(LatestStickerModel(288111, "https://drive.google.com/uc?export=download&id=10ZCHNvSw9mMuzZByJykIJeB6xel_1ewZ"))
            list.add(LatestStickerModel(289111, "https://drive.google.com/uc?export=download&id=1P0Vgg2MPJeQ5uPhSsKyQEO6jUz7ELCqV"))
            list.add(LatestStickerModel(290111, "https://drive.google.com/uc?export=download&id=1erDhO9ALULbhlz7QdRRHLdO05W3H-aHU"))
            list.add(LatestStickerModel(291111, "https://drive.google.com/uc?export=download&id=1PfRdSGoq3LT0dOulAPURfk9Jg7BFJZVa"))
            list.add(LatestStickerModel(292111, "https://drive.google.com/uc?export=download&id=1PTHir1gsn342xChM82DKoPlPLg_Sjc6N"))
            list.add(LatestStickerModel(293111, "https://drive.google.com/uc?export=download&id=1y90uRvo9XHncK0C3hK3gGv1-4ep_h4fj"))
            list.add(LatestStickerModel(294111, "https://drive.google.com/uc?export=download&id=1r1lvghmGzuW27agZ3w2SY52-GcaiN_ID"))
            list.add(LatestStickerModel(295111, "https://drive.google.com/uc?export=download&id=1R5ZtEOhEZVExpax1g3r-CmIZobBWINBX"))
            list.add(LatestStickerModel(296111, "https://drive.google.com/uc?export=download&id=1p3yEIkurWNpZiUwDFok7wpj06D_ZBgiz"))
            list.add(LatestStickerModel(297111, "https://drive.google.com/uc?export=download&id=1f3271FJwxmj6sYiw9Ai2NNnEQzGAXQBa"))
            list.add(LatestStickerModel(298111, "https://drive.google.com/uc?export=download&id=1G2eLvb0KaXgJhvzXwyxD-L9PwJ9CAtyY"))
            list.add(LatestStickerModel(299111, "https://drive.google.com/uc?export=download&id=1wWTdm62YXFN6ti-RveAL-VvLyphkEoCd"))
            list.add(LatestStickerModel(300111, "https://drive.google.com/uc?export=download&id=1ZjwBHo6O5o-9SqO7lFgyOuqIJnS4wvms"))
            return list
        }

    }
}